// sc2kfix modules/sc2k_1996.cpp: variables specific to the 1996 Special Edition version
// (c) 2025 sc2kfix project (https://sc2kfix.net) - released under the MIT license

// DO NOT USE THIS IN ANY OTHER FILE. I MEAN IT.
#define GAMEOFF_IMPL

#include <sc2kfix.h>

const char *getXTERNames(BYTE iVal) {
	if (iVal == TERRAIN_00)
		return "TERRAIN_00";
	else if (iVal == TERRAIN_01)
		return "TERRAIN_01";
	else if (iVal == TERRAIN_02)
		return "TERRAIN_02";
	else if (iVal == TERRAIN_03)
		return "TERRAIN_03";
	else if (iVal == TERRAIN_04)
		return "TERRAIN_04";
	else if (iVal == TERRAIN_05)
		return "TERRAIN_05";
	else if (iVal == TERRAIN_06)
		return "TERRAIN_06";
	else if (iVal == TERRAIN_07)
		return "TERRAIN_07";
	else if (iVal == TERRAIN_08)
		return "TERRAIN_08";
	else if (iVal == TERRAIN_09)
		return "TERRAIN_09";
	else if (iVal == TERRAIN_10)
		return "TERRAIN_10";
	else if (iVal == TERRAIN_11)
		return "TERRAIN_11";
	else if (iVal == TERRAIN_12)
		return "TERRAIN_12";
	else if (iVal == TERRAIN_13)
		return "TERRAIN_13";
	else if (iVal == SUBMERGED_00)
		return "SUBMERGED_00";
	else if (iVal == SUBMERGED_01)
		return "SUBMERGED_01";
	else if (iVal == SUBMERGED_02)
		return "SUBMERGED_02";
	else if (iVal == SUBMERGED_03)
		return "SUBMERGED_03";
	else if (iVal == SUBMERGED_04)
		return "SUBMERGED_04";
	else if (iVal == SUBMERGED_05)
		return "SUBMERGED_05";
	else if (iVal == SUBMERGED_06)
		return "SUBMERGED_06";
	else if (iVal == SUBMERGED_07)
		return "SUBMERGED_07";
	else if (iVal == SUBMERGED_08)
		return "SUBMERGED_08";
	else if (iVal == SUBMERGED_09)
		return "SUBMERGED_09";
	else if (iVal == SUBMERGED_10)
		return "SUBMERGED_10";
	else if (iVal == SUBMERGED_11)
		return "SUBMERGED_11";
	else if (iVal == SUBMERGED_12)
		return "SUBMERGED_12";
	else if (iVal == SUBMERGED_13)
		return "SUBMERGED_13";
	else if (iVal == COAST_00)
		return "COAST_00";
	else if (iVal == COAST_01)
		return "COAST_01";
	else if (iVal == COAST_02)
		return "COAST_02";
	else if (iVal == COAST_03)
		return "COAST_03";
	else if (iVal == COAST_04)
		return "COAST_04";
	else if (iVal == COAST_05)
		return "COAST_05";
	else if (iVal == COAST_06)
		return "COAST_06";
	else if (iVal == COAST_07)
		return "COAST_07";
	else if (iVal == COAST_08)
		return "COAST_08";
	else if (iVal == COAST_09)
		return "COAST_09";
	else if (iVal == COAST_10)
		return "COAST_10";
	else if (iVal == COAST_11)
		return "COAST_11";
	else if (iVal == COAST_12)
		return "COAST_12";
	else if (iVal == COAST_13)
		return "COAST_13";
	else if (iVal == SURFACE_WATER_00)
		return "SURFACE_WATER_00";
	else if (iVal == SURFACE_WATER_01)
		return "SURFACE_WATER_01";
	else if (iVal == SURFACE_WATER_02)
		return "SURFACE_WATER_02";
	else if (iVal == SURFACE_WATER_03)
		return "SURFACE_WATER_03";
	else if (iVal == SURFACE_WATER_04)
		return "SURFACE_WATER_04";
	else if (iVal == SURFACE_WATER_05)
		return "SURFACE_WATER_05";
	else if (iVal == SURFACE_WATER_06)
		return "SURFACE_WATER_06";
	else if (iVal == SURFACE_WATER_07)
		return "SURFACE_WATER_07";
	else if (iVal == SURFACE_WATER_08)
		return "SURFACE_WATER_08";
	else if (iVal == SURFACE_WATER_09)
		return "SURFACE_WATER_09";
	else if (iVal == SURFACE_WATER_10)
		return "SURFACE_WATER_10";
	else if (iVal == SURFACE_WATER_11)
		return "SURFACE_WATER_11";
	else if (iVal == SURFACE_WATER_12)
		return "SURFACE_WATER_12";
	else if (iVal == SURFACE_WATER_13)
		return "SURFACE_WATER_13";
	else if (iVal == WATERFALL)
		return "WATERFALL";
	else if (iVal == SURFACE_STREAM_00)
		return "SURFACE_STREAM_00";
	else if (iVal == SURFACE_STREAM_01)
		return "SURFACE_STREAM_01";
	else if (iVal == SURFACE_STREAM_02)
		return "SURFACE_STREAM_02";
	else if (iVal == SURFACE_STREAM_03)
		return "SURFACE_STREAM_03";
	else if (iVal == SURFACE_STREAM_04)
		return "SURFACE_STREAM_04";
	else if (iVal == SURFACE_STREAM_05)
		return "SURFACE_STREAM_05";
	else
		return "<invalid>";
}

const char* szTileNames[256] = {
	"Empty",
	"Rubble 1",
	"Rubble 2",
	"Rubble 3",
	"Rubble 4",
	"Radioactivity",
	"Tree",
	"Couple O' Trees",
	"More Trees",
	"Morer Trees",
	"Even More Trees",
	"Tons O' Trees",
	"Veritable Jungle",
	"Small Park",

	"Power Lines (LR)",
	"Power Lines (TB)",
	"Power Lines (HTB)",
	"Power Lines (LHR)",
	"Power Lines (THB)",
	"Power Lines (HLR)",
	"Power Lines (BR)",
	"Power Lines (BL)",
	"Power Lines (TL)",
	"Power Lines (TR)",
	"Power Lines (RTB)",
	"Power Lines (LBR)",
	"Power Lines (TLB)",
	"Power Lines (LTR)",
	"Power Lines (LTBR)",

	"Road (LR)",
	"Road (TB)",
	"Road (HTB)",
	"Road (LHR)",
	"Road (THB)",
	"Road (HLR)",
	"Road (BR)",
	"Road (BL)",
	"Road (TL)",
	"Road (TR)",
	"Road (RTB)",
	"Road (LBR)",
	"Road (TLB)",
	"Road (LTR)",
	"Road (LTBR)",

	"Rail (LR)",
	"Rail (TB)",
	"Rail (HTB)",
	"Rail (LHR)",
	"Rail (THB)",
	"Rail (HLR)",
	"Rail (BR)",
	"Rail (BL)",
	"Rail (TL)",
	"Rail (TR)",
	"Rail (RTB)",
	"Rail (LBR)",
	"Rail (TLB)",
	"Rail (LTR)",
	"Rail (LTBR)",
	"Rail (HHTB)",
	"Rail (LHHR)",
	"Rail (THHB)",
	"Rail (HHLR)",

	"Tunnel Entrance (Top)",
	"Tunnel Entrance (Right)",
	"Tunnel Entrance (Bottom)",
	"Tunnel Entrance (Left)",

	"Crossover (POWERTB_ROADLR)",
	"Crossover (POWERLR_ROADTB)",
	"Crossover (ROADLR_RAILTB)",
	"Crossover (ROADTB_RAILLR)",
	"Crossover (POWERTB_RAILLR)",
	"Crossover (POWERLR_RAILTB)",

	"Highway (LR)",
	"Highway (TB)",

	"Crossover (HIGHWAYLR_ROADTB)",
	"Crossover (HIGHWAYTB_ROADLR)",
	"Crossover (HIGHWAYLR_RAILTB)",
	"Crossover (HIGHWAYTB_RAILLR)",
	"Crossover (HIGHWAYLR_POWERTB)",
	"Crossover (HIGHWAYTB_POWERLR)",

	"Suspension Bridge (Start-B)",
	"Suspension Bridge (Middle-B)",
	"Suspension Bridge (Center-B)",
	"Suspension Bridge (Middle-T)",
	"Suspension Bridge (End-T)",
	"Raising Bridge (Tower)",
	"Causeway (Pylon)",
	"Raising Bridge (Lowered)",
	"Raising Bridge (Raised)",
	"Rail Bridge (Pylon)",
	"Rail Bridge",
	"Elevated Power Lines",

	"Onramp (TL)",
	"Onramp (TR)",
	"Onramp (BL)",
	"Onramp (BR)",

	"Highway (HTB)",
	"Highway (LHR)",
	"Highway (THB)",
	"Highway (HLR)",
	"Highway (BR)",
	"Highway (BL)",
	"Highway (TL)",
	"Highway (TR)",
	"Highway (LTBR)",

	"Reinforced Bridge (Pylon)",
	"Reinforced Bridge",

	"Subway-to-Rail Junction (Top)",
	"Subway-to-Rail Junction (Right)",
	"Subway-to-Rail Junction (Bottom)",
	"Subway-to-Rail Junction (Left)",

	"Lower-class Homes (1)",
	"Lower-class Homes (2)",
	"Lower-class Homes (3)",
	"Lower-class Homes (4)",
	"Middle-class Homes (1)",
	"Middle-class Homes (2)",
	"Middle-class Homes (3)",
	"Middle-class Homes (4)",
	"Luxury Homes (1)",
	"Luxury Homes (2)",
	"Luxury Homes (3)",
	"Luxury Homes (4)",

	"Gas Station (1)",
	"Bed and Breakfast",
	"Convenience Store",
	"Gas Station (2)",
	"Small Office Building (1)",
	"Small Office Building (2)",
	"Commercial Warehouse (1x1)",
	"Toy Store",

	"Small Warehouse (1)",
	"Chemical Storage",
	"Small Warehouse (2)",
	"Substation",

	"1x1 Construction (1)",
	"1x1 Construction (2)",
	"1x1 Abandoned Building (1)",
	"1x1 Abandoned Building (2)",

	"Small Apartments (1)",
	"Small Apartments (2)",
	"Small Apartments (3)",
	"Medium Apartments (1)",
	"Medium Apartments (2)",
	"Medium Condominums (1)",
	"Medium Condominums (2)",
	"Medium Condominums (3)",

	"Shopping Center",
	"Grocery Store",
	"Medium Office Building (1)",
	"Resort Hotel",
	"Medium Office Building (2)",
	"Office/Retail Building",
	"Medium Office Building (3)",
	"Medium Office Building (4)",
	"Medium Office Building (5)",
	"Medium Office Building (6)",

	"Medium Warehouse",
	"Chemical Processing",
	"Factory (1)",
	"Factory (2)",
	"Factory (3)",
	"Factory (4)",
	"Factory (5)",
	"Factory (6)",

	"2x2 Construction (1)",
	"2x2 Construction (2)",
	"2x2 Construction (3)",
	"2x2 Construction (4)",
	"2x2 Abandoned Building (1)",
	"2x2 Abandoned Building (2)",
	"2x2 Abandoned Building (3)",
	"2x2 Abandoned Building (4)",

	"Large Apartments (1)",
	"Large Apartments (2)",
	"Large Condominiums (1)",
	"Large Condominiums (2)",

	"Office Park",
	"Office Tower (1)",
	"Mini-Mall",
	"Theater Square",
	"Drive-In Theater",
	"Office Tower (2)",
	"Office Tower (3)",
	"Parking Lot",
	"Historic Office Building",
	"Corporate Headquarters",

	"Chemical Processing",
	"Large Factory",
	"Industrial Thingamajig",
	"Medium Factory",
	"Large Warehouse (1)",
	"Large Warehouse (2)",

	"3x3 Construction (1)",
	"3x3 Construction (2)",
	"3x3 Abandoned Building (1)",
	"3x3 Abandoned Building (2)",

	"Hydroelectric Power Plant (1)",
	"Hydroelectric Power Plant (2)",
	"Wind Power Plant",
	"Natural Gas Power Plant",
	"Oil Power Plant",
	"Nuclear Power Plant",
	"Solar Power Plant",
	"Microwave Power Plant",
	"Fusion Power Plant",
	"Coal Power Plant",

	"City Hall",
	"Hospital",
	"Police Station",
	"Fire Station",
	"Museum",
	"Large Park",
	"School",
	"Stadium",
	"Prison",
	"College",
	"Zoo",
	"Statue",

	"Water Pump",
	"Runway",
	"Runway (Cross)",
	"Pier",
	"Crane",
	"Civilan Control Tower",
	"Military Control Tower",
	"Military Warehouse",
	"Port Building (1)",
	"Port Building (2)",
	"Tarmac",
	"F-15B",
	"Military Hangar",
	"Subway Station",
	"Radar",
	"Water Tower",
	"Bus Depot",
	"Railway Station",
	"Parking Lot",
	"Military Parking Lot",
	"Loading Bay",
	"Top Secret",
	"Cargo Yard",
	"Mayor's House",
	"Water Treatment Plant",
	"Library",
	"Large Hangar",
	"Church",
	"Marina",
	"Missile Silo",
	"Desalinization Plant",

	"Plymouth Arcology",
	"Forest Arcology",
	"Darco Arcology",
	"Launch Arcology",

	"Braun-Llama Dome"
};

const char* szSpriteNames[SPRITE_ENTRY_COUNT] = {
	"None",
	"Rubble 1",
	"Rubble 2",
	"Rubble 3",
	"Rubble 4",
	"Radioactive Waste",
	"Trees (Tree)",
	"Trees (Couple O Trees)",
	"Trees (More Trees)",
	"Trees (Morer Trees)",
	"Trees (Even More Trees)",
	"Trees (Tons O Trees)",
	"Trees (Veritable Jungle)",
	"Small park",
	"Power Line [R-L]",
	"Power Line [T-B]",
	"Power Line [HT-B]",
	"Power Line [HR-L]",
	"Power Line [T-HB]",
	"Power Line [R-HL]",
	"Power Line [R-B]",
	"Power Line [B-L]",
	"Power Line [T-L]",
	"Power Line [T-R]",
	"Power Line [T-R-B]",
	"Power Line [R-B-L]",
	"Power Line [T-B-L]",
	"Power Line [T-R-L]",
	"Power Line [T-R-B-L]",
	"Road [R-L]",
	"Road [T-B]",
	"Road [HT-B]",
	"Road [HR-L]",
	"Road [T-HB]",
	"Road [R-HL]",
	"Road [R-B]",
	"Road [B-L]",
	"Road [T-L]",
	"Road [T-R]",
	"Road [T-R-B]",
	"Road [R-B-L]",
	"Road [T-B-L]",
	"Road [T-R-L]",
	"Road [T-R-B-L]",
	"Rail [R-L]",
	"Rail [T-B]",
	"Rail [HT-B]",
	"Rail [HR-L]",
	"Rail [T-HB]",
	"Rail [R-HL]",
	"Rail [R-B]",
	"Rail [B-L]",
	"Rail [T-L]",
	"Rail [T-R]",
	"Rail [T-R-B]",
	"Rail [R-B-L]",
	"Rail [T-B-L]",
	"Rail [T-R-L]",
	"Rail [T-R-B-L]",
	"Rail Slope [HT-B]",
	"Rail Slope [HR-L]",
	"Rail Slope [T-HB]",
	"Rail Slope [R-HL]",
	"Tunnel Entrance [B], Tunnel [T], Terrain [HT-B]",
	"Tunnel Entrance [L], Tunnel [R], Terrain [HR-L]",
	"Tunnel Entrance [T], Tunnel [B], Terrain [HB-T]",
	"Tunnel Entrance [R], Tunnel [L], Terrain [HL-R]",
	"Road [T-B], Power Line [R-L]",
	"Road [R-L], Power Line [T-B]",
	"Road [R-L] / Rail [T-B]",
	"Road [T-B] / Rail [R-L]",
	"Rail [T-B] / Power Line [R-L]",
	"Rail [R-L] / Power Line [T-B]",
	"Highway [L-R]",
	"Highway [T-B]",
	"Highway [R-L], Road [T-B]",
	"Highway [T-B], Road [R-L]",
	"Highway [R-L], Rail [T-B]",
	"Highway [T-B], Rail [R-L]",
	"Highway [R-L], Power Line [T-B]",
	"Highway [T-B], Power Line [R-L]",
	"Suspension Bridge (Piece 1) [R-L]",
	"Suspension Bridge (Piece 2) [R-L]",
	"Suspension Bridge (Piece 3) [R-L]",
	"Suspension Bridge (Piece 4) [R-L]",
	"Suspension Bridge (Piece 5) [R-L]",
	"Raising Bridge Tower [R-L]",
	"Causeway With Pylon [R-L]",
	"Causeway [R-L]",
	"Causeway Raised [R-L]",
	"Rail Bridge With Pylon [R-L]",
	"Rail Bridge [R-L]",
	"Elevated Power Line [B-L]",
	"Highway Onramp [R], Road [B]",
	"Highway Onramp [R], Road [T]",
	"Highway Onramp [L], Road [T]",
	"Highway Onramp [L], Road [B]",
	"Highway [HT-B]",
	"Highway [HR-L]",
	"Highway [T-HB]",
	"Highway [R-HL]",
	"Highway [R-B]",
	"Highway [B-L]",
	"Highway [T-L]",
	"Highway [T-R]",
	"Highway Interchange [T-R-B-L]",
	"Highway (Reinforced Bridge With Pylon) [R-L]",
	"Highway (Reinforced Bridge) [R-L]",
	"Subway [T] to Rail [B] Transition",
	"Subway [L] to Rail [R] Transition",
	"Subway [B] to Rail [T] Transition",
	"Subway [R] to Rail [L] Transition",
	"Lower-Class Homes",
	"Lower-Class Homes",
	"Lower-Class Homes",
	"Lower-Class Homes",
	"Middle-Class Homes",
	"Middle-Class Homes",
	"Middle-Class Homes",
	"Middle-Class Homes",
	"Luxury Homes",
	"Luxury Homes",
	"Luxury Homes",
	"Luxury Homes",
	"Gas Station",
	"Bed & Breakfast Inn",
	"Convenience Store",
	"Gas Station",
	"Small Office Building",
	"Office Building",
	"Warehouse",
	"Cassidy's Toy Store",
	"Warehouse",
	"Chemical Storage",
	"Warehouse",
	"Industrial Substation",
	"Construction 1",
	"Construction 2",
	"Abandoned Building 1",
	"Abandoned Building 2",
	"Cheap Apartments",
	"Apartments",
	"Apartments",
	"Nice Apartments",
	"Nice Apartments",
	"Condominium",
	"Condominium",
	"Condominium",
	"Shopping Center",
	"Grocery Store",
	"Office Building",
	"Resort Hotel",
	"Office Building",
	"Office / Retail",
	"Office Building",
	"Office Building",
	"Office Building",
	"Office Building",
	"Warehouse",
	"Chemical Processing 2",
	"Factory (Small Factory 1)",
	"Factory (Small Factory 2)",
	"Factory (Small Factory 3)",
	"Factory (Small Factory 4)",
	"Factory (Small Factory 5)",
	"Factory (Small Factory 6)",
	"Construction 3",
	"Construction 4",
	"Construction 5",
	"Construction 6",
	"Abandoned Building 3",
	"Abandoned Building 4",
	"Abandoned Building 5",
	"Abandoned Building 6",
	"Large Apartment Building",
	"Large Apartment Building",
	"Condominium",
	"Condominium",
	"Office Park",
	"Office Tower",
	"Mini-Mall",
	"Theater Square",
	"Drive-In Theater",
	"Office Tower",
	"Office Tower",
	"Parking Lot",
	"Historic Office Building",
	"Corporate Headquarters",
	"Chemical Processing 1",
	"Large Factory",
	"Industrial Thingamajig",
	"Factory",
	"Large Warehouse 1",
	"Warehouse",
	"Construction 7",
	"Construction 8",
	"Abandoned Building 7",
	"Abandoned Building 8",
	"Hydroelectric Power",
	"Hydroelectric Power",
	"Wind Power",
	"Natural Gas Power Plant",
	"Oil Power Plant",
	"Nuclear Power Plant",
	"Solar Power Plant",
	"Microwave Power Receiver",
	"Fusion Power Plant",
	"Coal Power Plant",
	"City Hall",
	"Hospital",
	"Police Station",
	"Fire Station",
	"Museum",
	"SimPark System (Big Park)",
	"School",
	"Stadium",
	"Prison",
	"College",
	"Zoo",
	"Statue",
	"Water Pump",
	"Runway [T-B]",
	"Runway [T-R-B-L]",
	"Pier [R-L]",
	"Crane",
	"Control Tower (Civilian Control Tower)",
	"Control Tower (Military Control Tower)",
	"Seaport Warehouse",
	"Airport Building 1",
	"Airport Building 2",
	"Tarmac",
	"F-15b",
	"Hangar 1",
	"Subway Station",
	"Radar",
	"Water Tower",
	"Bus Depot",
	"Rail Depot",
	"Parking lot (Civilian Parking Lot)",
	"Parking lot (Military Parking Lot)",
	"Loading Bay",
	"Top Secret",
	"Cargo yard",
	"Mayor's House",
	"Water Treatment Plant",
	"Library",
	"Hangar 2",
	"Church",
	"Marina",
	"Missile Silo",
	"Desalination Plant",
	"Plymouth arcology",
	"Forest arcology",
	"Darco arcology",
	"Launch arcology",
	"Braun Llama Dome",
	"Terrain",
	"Terrain [HT-B]",
	"Terrain [HR-L]",
	"Terrain [T-HB]",
	"Terrain [R-HL]",
	"Terrain [HT-HR-B-L]",
	"Terrain [T-HR-HB-L]",
	"Terrain [T-R-HB-HL]",
	"Terrain [HT-R-B-HL]",
	"Terrain Slope [HT-HR-B-L]",
	"Terrain Slope [T-HR-HB-L]",
	"Terrain Slope [T-R-HB-HL]",
	"Terrain Slope [HT-R-B-HL]",
	"Bedrock",
	"Water [T-R-B-L]",
	"Water [R-B-L], Terrain [T]",
	"Water [T-B-L], Terrain [R]",
	"Water [T-R-L], Terrain [B]",
	"Water [T-R-B], Terrain [L]",
	"Water [B-L], Terrain [T-R]",
	"Water [T-L], Terrain [R-B]",
	"Water [T-R], Terrain [B-L]",
	"Water [R-B], Terrain [T-L]",
	"Water [T-R-B]",
	"Water [R-B-L]",
	"Water [T-B-L]",
	"Water [T-R-L]",
	"Isolated Water, Terrain [T-R-B-L]",
	"Waterfall",
	"Water [R-L], Terrain [T-B]",
	"Water [T-B], Terrain [R-L]",
	"Water [B], Terrain [T-R-L]",
	"Water [L], Terrain [T-R-B]",
	"Water [T], Terrain [R-B-L]",
	"Water [R], Terrain [T-B-L]",
	"Low Density Residential Zone",
	"High Density Residential Zone",
	"Low Density Commercial Zone",
	"High Density Commercial Zone",
	"Low Density Industrial Zone",
	"High Density Industrial Zone",
	"Military Zone",
	"Airport Zone",
	"Seaport Zone",
	"Green Tile",
	"Blue Tile",
	"Yellow Tile",
	"Red Tile",
	"Grey Tile",
	"Underground Terrain",
	"Underground Terrain [HT-B]",
	"Underground Terrain [HR-L]",
	"Underground Terrain [T-HB]",
	"Underground Terrain [R-HL]",
	"Underground Terrain [HT-HR-B-L]",
	"Underground Terrain [T-HR-HB-L]",
	"Underground Terrain [T-R-HB-HL]",
	"Underground Terrain [HT-R-B-HL]",
	"Underground Terrain Slope [HT-HR-B-L]",
	"Underground Terrain Slope [T-HR-HB-L]",
	"Underground Terrain Slope [T-R-HB-HL]",
	"Underground Terrain Slope [HT-R-B-HL]",
	"Bedrock Outline",
	"Subway [R-L]",
	"Subway [T-B]",
	"Subway [HT-B]",
	"Subway [HR-L]",
	"Subway [T-HB]",
	"Subway [R-HL]",
	"Subway [R-B]",
	"Subway [B-L]",
	"Subway [T-L]",
	"Subway [T-R]",
	"Subway [T-R-B]",
	"Subway [R-B-L]",
	"Subway [T-B-L]",
	"Subway [T-R-L]",
	"Subway [T-R-B-L]",
	"Pipe [R-L]",
	"Pipe [T-B]",
	"Pipe [HT-B]",
	"Pipe [HR-L]",
	"Pipe [T-HB]",
	"Pipe [R-HL]",
	"Pipe [R-B]",
	"Pipe [B-L]",
	"Pipe [T-L]",
	"Pipe [T-R]",
	"Pipe [T-R-B]",
	"Pipe [R-B-L]",
	"Pipe [T-B-L]",
	"Pipe [T-R-L]",
	"Pipe [T-R-B-L]",
	"Subway [R-L], Pipe [T-B]",
	"Subway [T-B], Pipe [R-L]",
	"Building Pipe [T-R-B-L]",
	"Underground Segment (single)",
	"Underground Segment (double)",
	"Green Outline",
	"Blue Outline",
	"Brown Outline",
	"Red Outline",
	"Grey Outline",
	"Airplane [N]",
	"Airplane [NE]",
	"Airplane [E]",
	"Airplane [SE]",
	"Airplane [S]",
	"Sim Copter [N]",
	"Sim Copter [NE]",
	"Sim Copter [E]",
	"Sim Copter [SE]",
	"Sim Copter [S]",
	"Cargo Ship [N]",
	"Cargo Ship [NE]",
	"Cargo Ship [E]",
	"Cargo Ship [SE]",
	"Cargo Ship [S]",
	"Train [N]",
	"Train [NE]",
	"Train [E]",
	"Train [SE]",
	"Train [S]",
	"Nessie",
	"Sail Boat [NE]",
	"Sail Boat [SE]",
	"Police Dispatch",
	"Fire Dept. Dispatch",
	"Military Dispatch",
	"Monster Space Ray",
	"Power Outage Indicator",
	"Explosion 1",
	"Explosion 2",
	"Explosion 3",
	"Bulldozer [NE]",
	"Bulldozer [SE]",
	"Dust Cloud 1",
	"Dust Cloud 2",
	"Dust Cloud 3",
	"Dust Cloud 4",
	"Fire 1",
	"Fire 2",
	"Fire 3",
	"Fire 4",
	"Road Light Traffic [R-L]",
	"Road Light Traffic [T-B]",
	"Road Light Traffic [HT-B]",
	"Road Light Traffic [HR-L]",
	"Road Light Traffic [T-HB]",
	"Road Light Traffic [R-HL]",
	"Road Light Traffic [R-B]",
	"Road Light Traffic [B-L]",
	"Road Light Traffic [T-L]",
	"Road Light Traffic [T-R]",
	"Highway Light Traffic [R-L]",
	"Highway Light Traffic [T-B]",
	"Causeway Light Traffic [R-L]",
	"Causeway Light Traffic [T-B]",
	"Highway On-Ramp Light Traffic [R-B]",
	"Highway On-Ramp Light Traffic [T-R]",
	"Highway On-Ramp Light Traffic [R-T]",
	"Highway On-Ramp Light Traffic [B-L]",
	"Highway Light Traffic [HT-B]",
	"Highway Light Traffic [HR-L]",
	"Highway Light Traffic [T-HB]",
	"Highway Light Traffic [R-HL]",
	"Highway Light Traffic [R-B]",
	"Highway Light Traffic [B-L]",
	"Highway Light Traffic [T-L]",
	"Highway Light Traffic [T-R]",
	"Highway Interchange Light Traffic [T-R-B-L]",
	"Road Heavy Traffic [R-L]",
	"Road Heavy Traffic [T-B]",
	"Road Heavy Traffic [HT-B]",
	"Road Heavy Traffic [HR-L]",
	"Road Heavy Traffic [T-HB]",
	"Road Heavy Traffic [R-HL]",
	"Road Heavy Traffic [R-B]",
	"Road Heavy Traffic [B-L]",
	"Road Heavy Traffic [T-L]",
	"Road Heavy Traffic [T-R]",
	"Highway Heavy Traffic [R-L]",
	"Highway Heavy Traffic [T-B]",
	"Causeway Heavy Traffic [R-L]",
	"Causeway Heavy Traffic [T-B]",
	"Highway Heavy Traffic [HT-B]",
	"Highway Heavy Traffic [HR-L]",
	"Highway Heavy Traffic [T-HB]",
	"Highway Heavy Traffic [R-HL]",
	"Highway Heavy Traffic [R-B]",
	"Highway Heavy Traffic [B-L]",
	"Highway Heavy Traffic [T-L]",
	"Highway Heavy Traffic [T-R]",
	"Highway Heavy Traffic [T-R-B-L]",
	"Pipe Watered [R-L]",
	"Pipe Watered [T-B]",
	"Pipe Watered [HT-B]",
	"Pipe Watered [HR-L]",
	"Pipe Watered [T-HB]",
	"Pipe Watered [R-HL]",
	"Pipe Watered [R-B]",
	"Pipe Watered [B-L]",
	"Pipe Watered [T-L]",
	"Pipe Watered [T-R]",
	"Pipe Watered [T-R-B]",
	"Pipe Watered [R-B-L]",
	"Pipe Watered [T-B-L]",
	"Pipe Watered [T-R-L]",
	"Pipe Watered [T-R-B-L]",
	"Subway [R-L], Pipe Watered [T-B]",
	"Subway [T-B], Pipe Watered [R-L]",
	"Building Pipe Watered [T-R-B-L]",
	"Density Overlay 1",
	"Density Overlay 2",
	"Density Overlay 3",
	"Density Overlay 4",
	"Density Overlay 5",
	"Density Overlay 6",
	"Density Overlay 7",
	"Density Overlay 8",
	"Green Plus",
	"Red Negative",
	"Monster Parts 1",
	"Monster Parts 2",
	"Monster Parts 3",
	"Monster Parts 4",
	"Monster Parts 5",
	"Monster Parts 6",
	"Monster Parts 7",
	"Monster Parts 8",
	"Monster Parts 9",
	"Monster Parts 10",
	"Monster Parts 11",
	"Monster Parts 12",
	"Monster Parts 13",
	"Monster Parts 14",
	"Flood Water",
	"Rioters 1",
	"Rioters 2",
	"Maxis Man",
	"Dust Cloud",
	"Tornado 1",
	"Tornado 2",
	"Tornado 3"
};

const char *szInternalSpriteName[SPRITE_COUNT] = {
	"SPRITE_SMALL_CLEAR",
	"SPRITE_SMALL_RUBBLE1",
	"SPRITE_SMALL_RUBBLE2",
	"SPRITE_SMALL_RUBBLE3",
	"SPRITE_SMALL_RUBBLE4",
	"SPRITE_SMALL_RADIOACTIVITY",
	"SPRITE_SMALL_TREES1",
	"SPRITE_SMALL_TREES2",
	"SPRITE_SMALL_TREES3",
	"SPRITE_SMALL_TREES4",
	"SPRITE_SMALL_TREES5",
	"SPRITE_SMALL_TREES6",
	"SPRITE_SMALL_TREES7",
	"SPRITE_SMALL_SMALLPARK",
	"SPRITE_SMALL_POWERLINES_LR",
	"SPRITE_SMALL_POWERLINES_TB",
	"SPRITE_SMALL_POWERLINES_HTB",
	"SPRITE_SMALL_POWERLINES_LHR",
	"SPRITE_SMALL_POWERLINES_THB",
	"SPRITE_SMALL_POWERLINES_HLR",
	"SPRITE_SMALL_POWERLINES_BR",
	"SPRITE_SMALL_POWERLINES_BL",
	"SPRITE_SMALL_POWERLINES_TL",
	"SPRITE_SMALL_POWERLINES_TR",
	"SPRITE_SMALL_POWERLINES_RTB",
	"SPRITE_SMALL_POWERLINES_LBR",
	"SPRITE_SMALL_POWERLINES_TLB",
	"SPRITE_SMALL_POWERLINES_LTR",
	"SPRITE_SMALL_POWERLINES_LTBR",
	"SPRITE_SMALL_ROAD_LR",
	"SPRITE_SMALL_ROAD_TB",
	"SPRITE_SMALL_ROAD_HTB",
	"SPRITE_SMALL_ROAD_LHR",
	"SPRITE_SMALL_ROAD_THB",
	"SPRITE_SMALL_ROAD_HLR",
	"SPRITE_SMALL_ROAD_BR",
	"SPRITE_SMALL_ROAD_BL",
	"SPRITE_SMALL_ROAD_TL",
	"SPRITE_SMALL_ROAD_TR",
	"SPRITE_SMALL_ROAD_RTB",
	"SPRITE_SMALL_ROAD_LBR",
	"SPRITE_SMALL_ROAD_TLB",
	"SPRITE_SMALL_ROAD_LTR",
	"SPRITE_SMALL_ROAD_LTBR",
	"SPRITE_SMALL_RAIL_LR",
	"SPRITE_SMALL_RAIL_TB",
	"SPRITE_SMALL_RAIL_HTB",
	"SPRITE_SMALL_RAIL_LHR",
	"SPRITE_SMALL_RAIL_THB",
	"SPRITE_SMALL_RAIL_HLR",
	"SPRITE_SMALL_RAIL_BR",
	"SPRITE_SMALL_RAIL_BL",
	"SPRITE_SMALL_RAIL_TL",
	"SPRITE_SMALL_RAIL_TR",
	"SPRITE_SMALL_RAIL_RTB",
	"SPRITE_SMALL_RAIL_LBR",
	"SPRITE_SMALL_RAIL_TLB",
	"SPRITE_SMALL_RAIL_LTR",
	"SPRITE_SMALL_RAIL_LTBR",
	"SPRITE_SMALL_RAIL_HHTB",
	"SPRITE_SMALL_RAIL_LHHR",
	"SPRITE_SMALL_RAIL_THHB",
	"SPRITE_SMALL_RAIL_HHLR",
	"SPRITE_SMALL_TUNNEL_T",
	"SPRITE_SMALL_TUNNEL_R",
	"SPRITE_SMALL_TUNNEL_B",
	"SPRITE_SMALL_TUNNEL_L",
	"SPRITE_SMALL_CROSSOVER_POWERTB_ROADLR",
	"SPRITE_SMALL_CROSSOVER_POWERLR_ROADTB",
	"SPRITE_SMALL_CROSSOVER_ROADLR_RAILTB",
	"SPRITE_SMALL_CROSSOVER_ROADTB_RAILLR",
	"SPRITE_SMALL_CROSSOVER_POWERTB_RAILLR",
	"SPRITE_SMALL_CROSSOVER_POWERLR_RAILTB",
	"SPRITE_SMALL_HIGHWAY_LR",
	"SPRITE_SMALL_HIGHWAY_TB",
	"SPRITE_SMALL_CROSSOVER_HIGHWAYLR_ROADTB",
	"SPRITE_SMALL_CROSSOVER_HIGHWAYTB_ROADLR",
	"SPRITE_SMALL_CROSSOVER_HIGHWAYLR_RAILTB",
	"SPRITE_SMALL_CROSSOVER_HIGHWAYTB_RAILLR",
	"SPRITE_SMALL_CROSSOVER_HIGHWAYLR_POWERTB",
	"SPRITE_SMALL_CROSSOVER_HIGHWAYTB_POWERLR",
	"SPRITE_SMALL_SUSPENSION_BRIDGE_START_B",
	"SPRITE_SMALL_SUSPENSION_BRIDGE_MIDDLE_B",
	"SPRITE_SMALL_SUSPENSION_BRIDGE_CENTER_B",
	"SPRITE_SMALL_SUSPENSION_BRIDGE_MIDDLE_T",
	"SPRITE_SMALL_SUSPENSION_BRIDGE_END_T",
	"SPRITE_SMALL_RAISING_BRIDGE_TOWER",
	"SPRITE_SMALL_CAUSEWAY_PYLON",
	"SPRITE_SMALL_RAISING_BRIDGE_LOWERED",
	"SPRITE_SMALL_RAISING_BRIDGE_RAISED",
	"SPRITE_SMALL_RAIL_BRIDGE_PYLON",
	"SPRITE_SMALL_RAIL_BRIDGE",
	"SPRITE_SMALL_ELEVATED_POWERLINES",
	"SPRITE_SMALL_ONRAMP_TL",
	"SPRITE_SMALL_ONRAMP_TR",
	"SPRITE_SMALL_ONRAMP_BL",
	"SPRITE_SMALL_ONRAMP_BR",
	"SPRITE_SMALL_HIGHWAY_HTB",
	"SPRITE_SMALL_HIGHWAY_LHR",
	"SPRITE_SMALL_HIGHWAY_THB",
	"SPRITE_SMALL_HIGHWAY_HLR",
	"SPRITE_SMALL_HIGHWAY_BR",
	"SPRITE_SMALL_HIGHWAY_BL",
	"SPRITE_SMALL_HIGHWAY_TL",
	"SPRITE_SMALL_HIGHWAY_TR",
	"SPRITE_SMALL_HIGHWAY_LTBR",
	"SPRITE_SMALL_REINFORCED_BRIDGE_PYLON",
	"SPRITE_SMALL_REINFORCED_BRIDGE",
	"SPRITE_SMALL_SUBTORAIL_T",
	"SPRITE_SMALL_SUBTORAIL_R",
	"SPRITE_SMALL_SUBTORAIL_B",
	"SPRITE_SMALL_SUBTORAIL_L",
	"SPRITE_SMALL_RESIDENTIAL_1X1_LOWERCLASSHOMES1",
	"SPRITE_SMALL_RESIDENTIAL_1X1_LOWERCLASSHOMES2",
	"SPRITE_SMALL_RESIDENTIAL_1X1_LOWERCLASSHOMES3",
	"SPRITE_SMALL_RESIDENTIAL_1X1_LOWERCLASSHOMES4",
	"SPRITE_SMALL_RESIDENTIAL_1X1_MIDDLECLASSHOMES1",
	"SPRITE_SMALL_RESIDENTIAL_1X1_MIDDLECLASSHOMES2",
	"SPRITE_SMALL_RESIDENTIAL_1X1_MIDDLECLASSHOMES3",
	"SPRITE_SMALL_RESIDENTIAL_1X1_MIDDLECLASSHOMES4",
	"SPRITE_SMALL_RESIDENTIAL_1X1_UPPERCLASSHOMES1",
	"SPRITE_SMALL_RESIDENTIAL_1X1_UPPERCLASSHOMES2",
	"SPRITE_SMALL_RESIDENTIAL_1X1_UPPERCLASSHOMES3",
	"SPRITE_SMALL_RESIDENTIAL_1X1_UPPERCLASSHOMES4",
	"SPRITE_SMALL_COMMERCIAL_1X1_GASSTATION1",
	"SPRITE_SMALL_COMMERCIAL_1X1_BEDANDBREAKFAST",
	"SPRITE_SMALL_COMMERCIAL_1X1_CONVENIENCESTORE",
	"SPRITE_SMALL_COMMERCIAL_1X1_GASSTATION2",
	"SPRITE_SMALL_COMMERCIAL_1X1_SMALLOFFICEBUILDING1",
	"SPRITE_SMALL_COMMERCIAL_1X1_SMALLOFFICEBUILDING2",
	"SPRITE_SMALL_COMMERCIAL_1X1_WAREHOUSE",
	"SPRITE_SMALL_COMMERCIAL_1X1_TOYSTORE",
	"SPRITE_SMALL_INDUSTRIAL_1X1_SMALLWAREHOUSE1",
	"SPRITE_SMALL_INDUSTRIAL_1X1_CHEMICALSTORAGE",
	"SPRITE_SMALL_INDUSTRIAL_1X1_SMALLWAREHOUSE2",
	"SPRITE_SMALL_INDUSTRIAL_1X1_SUBSTATION",
	"SPRITE_SMALL_MISC_1X1_CONSTRUCTION1",
	"SPRITE_SMALL_MISC_1X1_CONSTRUCTION2",
	"SPRITE_SMALL_MISC_1X1_ABANDONED1",
	"SPRITE_SMALL_MISC_1X1_ABANDONED2",
	"SPRITE_SMALL_RESIDENTIAL_2X2_SMALLAPARTMENTS1",
	"SPRITE_SMALL_RESIDENTIAL_2X2_SMALLAPARTMENTS2",
	"SPRITE_SMALL_RESIDENTIAL_2X2_SMALLAPARTMENTS3",
	"SPRITE_SMALL_RESIDENTIAL_2X2_MEDIUMAPARTMENTS1",
	"SPRITE_SMALL_RESIDENTIAL_2X2_MEDIUMAPARTMENTS2",
	"SPRITE_SMALL_RESIDENTIAL_2X2_MEDIUMCONDOS1",
	"SPRITE_SMALL_RESIDENTIAL_2X2_MEDIUMCONDOS2",
	"SPRITE_SMALL_RESIDENTIAL_2X2_MEDIUMCONDOS3",
	"SPRITE_SMALL_COMMERCIAL_2X2_SHOPPINGCENTER",
	"SPRITE_SMALL_COMMERCIAL_2X2_GROCERYSTORE",
	"SPRITE_SMALL_COMMERCIAL_2X2_MEDIUMOFFICE1",
	"SPRITE_SMALL_COMMERCIAL_2X2_RESORTHOTEL",
	"SPRITE_SMALL_COMMERCIAL_2X2_MEDIUMOFFICE2",
	"SPRITE_SMALL_COMMERCIAL_2X2_OFFICERETAIL",
	"SPRITE_SMALL_COMMERCIAL_2X2_MEDIUMOFFICE3",
	"SPRITE_SMALL_COMMERCIAL_2X2_MEDIUMOFFICE4",
	"SPRITE_SMALL_COMMERCIAL_2X2_MEDIUMOFFICE5",
	"SPRITE_SMALL_COMMERCIAL_2X2_MEDIUMOFFICE6",
	"SPRITE_SMALL_INDUSTRIAL_2X2_MEDIUMWAREHOUSE",
	"SPRITE_SMALL_INDUSTRIAL_2X2_CHEMICALPROCESSING",
	"SPRITE_SMALL_INDUSTRIAL_2X2_FACTORY1",
	"SPRITE_SMALL_INDUSTRIAL_2X2_FACTORY2",
	"SPRITE_SMALL_INDUSTRIAL_2X2_FACTORY3",
	"SPRITE_SMALL_INDUSTRIAL_2X2_FACTORY4",
	"SPRITE_SMALL_INDUSTRIAL_2X2_FACTORY5",
	"SPRITE_SMALL_INDUSTRIAL_2X2_FACTORY6",
	"SPRITE_SMALL_MISC_2X2_CONSTRUCTION1",
	"SPRITE_SMALL_MISC_2X2_CONSTRUCTION2",
	"SPRITE_SMALL_MISC_2X2_CONSTRUCTION3",
	"SPRITE_SMALL_MISC_2X2_CONSTRUCTION4",
	"SPRITE_SMALL_MISC_2X2_ABANDONED1",
	"SPRITE_SMALL_MISC_2X2_ABANDONED2",
	"SPRITE_SMALL_MISC_2X2_ABANDONED3",
	"SPRITE_SMALL_MISC_2X2_ABANDONED4",
	"SPRITE_SMALL_RESIDENTIAL_3X3_LARGEAPARTMENTS1",
	"SPRITE_SMALL_RESIDENTIAL_3X3_LARGEAPARTMENTS2",
	"SPRITE_SMALL_RESIDENTIAL_3X3_LARGECONDOS1",
	"SPRITE_SMALL_RESIDENTIAL_3X3_LARGECONDOS2",
	"SPRITE_SMALL_COMMERCIAL_3X3_OFFICEPARK",
	"SPRITE_SMALL_COMMERCIAL_3X3_OFFICETOWER1",
	"SPRITE_SMALL_COMMERCIAL_3X3_MINIMALL",
	"SPRITE_SMALL_COMMERCIAL_3X3_THEATERSQUARE",
	"SPRITE_SMALL_COMMERCIAL_3X3_DRIVEINTHEATER",
	"SPRITE_SMALL_COMMERCIAL_3X3_OFFICETOWER2",
	"SPRITE_SMALL_COMMERCIAL_3X3_OFFICETOWER3",
	"SPRITE_SMALL_COMMERCIAL_3X3_PARKINGLOT",
	"SPRITE_SMALL_COMMERCIAL_3X3_HISTORICOFFICE",
	"SPRITE_SMALL_COMMERCIAL_3X3_CORPORATEHQ",
	"SPRITE_SMALL_INDUSTRIAL_3X3_CHEMICALPROCESSING",
	"SPRITE_SMALL_INDUSTRIAL_3X3_LARGEFACTORY",
	"SPRITE_SMALL_INDUSTRIAL_3X3_THINGAMAJIG",
	"SPRITE_SMALL_INDUSTRIAL_3X3_MEDIUMFACTORY",
	"SPRITE_SMALL_INDUSTRIAL_3X3_LARGEWAREHOUSE1",
	"SPRITE_SMALL_INDUSTRIAL_3X3_LARGEWAREHOUSE2",
	"SPRITE_SMALL_MISC_3X3_CONSTRUCTION1",
	"SPRITE_SMALL_MISC_3X3_CONSTRUCTION2",
	"SPRITE_SMALL_MISC_3X3_ABANDONED1",
	"SPRITE_SMALL_MISC_3X3_ABANDONED2",
	"SPRITE_SMALL_POWERPLANT_HYDRO1",
	"SPRITE_SMALL_POWERPLANT_HYDRO2",
	"SPRITE_SMALL_POWERPLANT_WIND",
	"SPRITE_SMALL_POWERPLANT_GAS",
	"SPRITE_SMALL_POWERPLANT_OIL",
	"SPRITE_SMALL_POWERPLANT_NUCLEAR",
	"SPRITE_SMALL_POWERPLANT_SOLAR",
	"SPRITE_SMALL_POWERPLANT_MICROWAVE",
	"SPRITE_SMALL_POWERPLANT_FUSION",
	"SPRITE_SMALL_POWERPLANT_COAL",
	"SPRITE_SMALL_SERVICES_CITYHALL",
	"SPRITE_SMALL_SERVICES_HOSPITAL",
	"SPRITE_SMALL_SERVICES_POLICE",
	"SPRITE_SMALL_SERVICES_FIRE",
	"SPRITE_SMALL_SERVICES_MUSEUM",
	"SPRITE_SMALL_SERVICES_BIGPARK",
	"SPRITE_SMALL_SERVICES_SCHOOL",
	"SPRITE_SMALL_SERVICES_STADIUM",
	"SPRITE_SMALL_SERVICES_PRISON",
	"SPRITE_SMALL_SERVICES_COLLEGE",
	"SPRITE_SMALL_SERVICES_ZOO",
	"SPRITE_SMALL_SERVICES_STATUE",
	"SPRITE_SMALL_INFRASTRUCTURE_WATERPUMP",
	"SPRITE_SMALL_INFRASTRUCTURE_RUNWAY",
	"SPRITE_SMALL_INFRASTRUCTURE_RUNWAYCROSS",
	"SPRITE_SMALL_INFRASTRUCTURE_PIER",
	"SPRITE_SMALL_INFRASTRUCTURE_CRANE",
	"SPRITE_SMALL_INFRASTRUCTURE_CONTROLTOWER_CIV",
	"SPRITE_SMALL_MILITARY_CONTROLTOWER",
	"SPRITE_SMALL_MILITARY_WAREHOUSE",
	"SPRITE_SMALL_INFRASTRUCTURE_BUILDING1",
	"SPRITE_SMALL_INFRASTRUCTURE_BUILDING2",
	"SPRITE_SMALL_MILITARY_TARMAC",
	"SPRITE_SMALL_MILITARY_F15B",
	"SPRITE_SMALL_MILITARY_HANGAR1",
	"SPRITE_SMALL_INFRASTRUCTURE_SUBWAYSTATION",
	"SPRITE_SMALL_MILITARY_RADAR",
	"SPRITE_SMALL_INFRASTRUCTURE_WATERTOWER",
	"SPRITE_SMALL_INFRASTRUCTURE_BUSDEPOT",
	"SPRITE_SMALL_INFRASTRUCTURE_RAILSTATION",
	"SPRITE_SMALL_INFRASTRUCTURE_PARKINGLOT",
	"SPRITE_SMALL_MILITARY_PARKINGLOT",
	"SPRITE_SMALL_MILITARY_LOADINGBAY",
	"SPRITE_SMALL_MILITARY_TOPSECRET",
	"SPRITE_SMALL_INFRASTRUCTURE_CARGOYARD",
	"SPRITE_SMALL_INFRASTRUCTURE_MAYORSHOUSE",
	"SPRITE_SMALL_INFRASTRUCTURE_WATERTREATMENT",
	"SPRITE_SMALL_INFRASTRUCTURE_LIBRARY",
	"SPRITE_SMALL_INFRASTRUCTURE_HANGAR2",
	"SPRITE_SMALL_INFRASTRUCTURE_CHURCH",
	"SPRITE_SMALL_INFRASTRUCTURE_MARINA",
	"SPRITE_SMALL_MILITARY_MISSILESILO",
	"SPRITE_SMALL_INFRASTRUCUTRE_DESALINIZATIONPLANT",
	"SPRITE_SMALL_ARCOLOGY_PLYMOUTH",
	"SPRITE_SMALL_ARCOLOGY_FOREST",
	"SPRITE_SMALL_ARCOLOGY_DARCO",
	"SPRITE_SMALL_ARCOLOGY_LAUNCH",
	"SPRITE_SMALL_OTHER_BRAUNLLAMADOME",
	"SPRITE_SMALL_TERRAIN",
	"SPRITE_SMALL_TERRAIN_HTB",
	"SPRITE_SMALL_TERRAIN_HRL",
	"SPRITE_SMALL_TERRAIN_THB",
	"SPRITE_SMALL_TERRAIN_RHL",
	"SPRITE_SMALL_TERRAIN_HTHRBL",
	"SPRITE_SMALL_TERRAIN_THRHBL",
	"SPRITE_SMALL_TERRAIN_TRHBHL",
	"SPRITE_SMALL_TERRAIN_HTRBHL",
	"SPRITE_SMALL_TERRAINSLOPE_HTHRBL",
	"SPRITE_SMALL_TERRAINSLOPE_THRHBL",
	"SPRITE_SMALL_TERRAINSLOPE_TRHBHL",
	"SPRITE_SMALL_TERRAINSLOPE_HTRBHL",
	"SPRITE_SMALL_BEDROCK",
	"SPRITE_SMALL_WATER_TRBL",
	"SPRITE_SMALL_WATER_RBL_TERRAIN_T",
	"SPRITE_SMALL_WATER_TBL_TERRAIN_R",
	"SPRITE_SMALL_WATER_TRL_TERRAIN_B",
	"SPRITE_SMALL_WATER_TRB_TERRAIN_L",
	"SPRITE_SMALL_WATER_BL_TERRAIN_TR",
	"SPRITE_SMALL_WATER_TL_TERRAIN_RB",
	"SPRITE_SMALL_WATER_TR_TERRAIN_BL",
	"SPRITE_SMALL_WATER_RB_TERRAIN_TL",
	"SPRITE_SMALL_WATER_TRB",
	"SPRITE_SMALL_WATER_RBL",
	"SPRITE_SMALL_WATER_TBL",
	"SPRITE_SMALL_WATER_TRL",
	"SPRITE_SMALL_ISOLATEDWATER_TERRAIN_TRBL",
	"SPRITE_SMALL_WATERFALL",
	"SPRITE_SMALL_WATER_RL_TERRAIN_TB",
	"SPRITE_SMALL_WATER_TB_TERRAIN_RL",
	"SPRITE_SMALL_WATER_B_TERRAIN_TRL",
	"SPRITE_SMALL_WATER_L_TERRAIN_TRB",
	"SPRITE_SMALL_WATER_T_TERRAIN_RBL",
	"SPRITE_SMALL_WATER_R_TERRAIN_TBL",
	"SPRITE_SMALL_LOWDENSITY_RESIDENTIALZONE",
	"SPRITE_SMALL_HIGHDENSITY_RESIDENTIALZONE",
	"SPRITE_SMALL_LOWDENSITY_COMMERCIALZONE",
	"SPRITE_SMALL_HIGHDENSITY_COMMERCIALZONE",
	"SPRITE_SMALL_LOWDENSITY_INDUSTRIALZONE",
	"SPRITE_SMALL_HIGHDENSITY_INDUSTRIALZONE",
	"SPRITE_SMALL_MILITARYZONE",
	"SPRITE_SMALL_AIRPORTZONE",
	"SPRITE_SMALL_SEAPORTZONE",
	"SPRITE_SMALL_GREENTILE",
	"SPRITE_SMALL_BLUETILE",
	"SPRITE_SMALL_YELLOWTILE",
	"SPRITE_SMALL_REDTILE",
	"SPRITE_SMALL_GREYTILE",
	"SPRITE_SMALL_UNDERGROUND_TERRAIN",
	"SPRITE_SMALL_UNDERGROUND_TERRAIN_HTB",
	"SPRITE_SMALL_UNDERGROUND_TERRAIN_HRL",
	"SPRITE_SMALL_UNDERGROUND_TERRAIN_THB",
	"SPRITE_SMALL_UNDERGROUND_TERRAIN_RHL",
	"SPRITE_SMALL_UNDERGROUND_TERRAIN_HTHRBL",
	"SPRITE_SMALL_UNDERGROUND_TERRAIN_THRHBL",
	"SPRITE_SMALL_UNDERGROUND_TERRAIN_TRHBHL",
	"SPRITE_SMALL_UNDERGROUND_TERRAIN_HTRBHL",
	"SPRITE_SMALL_UNDERGROUND_TERRAINSLOPE_HTHRBL",
	"SPRITE_SMALL_UNDERGROUND_TERRAINSLOPE_THRHBL",
	"SPRITE_SMALL_UNDERGROUND_TERRAINSLOPE_TRHBHL",
	"SPRITE_SMALL_UNDERGROUND_TERRAINSLOPE_HTRBHL",
	"SPRITE_SMALL_BEDROCK_OUTLINE",
	"SPRITE_SMALL_SUBWAY_LR",
	"SPRITE_SMALL_SUBWAY_TB",
	"SPRITE_SMALL_SUBWAY_HTB",
	"SPRITE_SMALL_SUBWAY_LHR",
	"SPRITE_SMALL_SUBWAY_THB",
	"SPRITE_SMALL_SUBWAY_HLR",
	"SPRITE_SMALL_SUBWAY_BR",
	"SPRITE_SMALL_SUBWAY_BL",
	"SPRITE_SMALL_SUBWAY_TL",
	"SPRITE_SMALL_SUBWAY_TR",
	"SPRITE_SMALL_SUBWAY_RTB",
	"SPRITE_SMALL_SUBWAY_LBR",
	"SPRITE_SMALL_SUBWAY_TLB",
	"SPRITE_SMALL_SUBWAY_LTR",
	"SPRITE_SMALL_SUBWAY_LTBR",
	"SPRITE_SMALL_PIPES_LR",
	"SPRITE_SMALL_PIPES_TB",
	"SPRITE_SMALL_PIPES_HTB",
	"SPRITE_SMALL_PIPES_LHR",
	"SPRITE_SMALL_PIPES_THB",
	"SPRITE_SMALL_PIPES_HLR",
	"SPRITE_SMALL_PIPES_BR",
	"SPRITE_SMALL_PIPES_BL",
	"SPRITE_SMALL_PIPES_TL",
	"SPRITE_SMALL_PIPES_TR",
	"SPRITE_SMALL_PIPES_RTB",
	"SPRITE_SMALL_PIPES_LBR",
	"SPRITE_SMALL_PIPES_TLB",
	"SPRITE_SMALL_PIPES_LTR",
	"SPRITE_SMALL_PIPES_LTBR",
	"SPRITE_SMALL_CROSSOVER_PIPESTB_SUBWAYLR",
	"SPRITE_SMALL_CROSSOVER_PIPESLR_SUBWAYTB",
	"SPRITE_SMALL_BUILDINGPIPE",
	"SPRITE_SMALL_MISSILESILO",
	"SPRITE_SMALL_SUBWAYENTRANCE",
	"SPRITE_SMALL_GREENOUTLINE",
	"SPRITE_SMALL_BLUEOUTLINE",
	"SPRITE_SMALL_BROWNOUTLINE",
	"SPRITE_SMALL_REDOUTLINE",
	"SPRITE_SMALL_GREYOUTLINE",
	"SPRITE_SMALL_AIRPLANE_N",
	"SPRITE_SMALL_AIRPLANE_NE",
	"SPRITE_SMALL_AIRPLANE_E",
	"SPRITE_SMALL_AIRPLANE_SE",
	"SPRITE_SMALL_AIRPLANE_S",
	"SPRITE_SMALL_SIMCOPTER_N",
	"SPRITE_SMALL_SIMCOPTER_NE",
	"SPRITE_SMALL_SIMCOPTER_E",
	"SPRITE_SMALL_SIMCOPTER_SE",
	"SPRITE_SMALL_SIMCOPTER_S",
	"SPRITE_SMALL_CARGOSHIP_N",
	"SPRITE_SMALL_CARGOSHIP_NE",
	"SPRITE_SMALL_CARGOSHIP_E",
	"SPRITE_SMALL_CARGOSHIP_SE",
	"SPRITE_SMALL_CARGOSHIP_S",
	"SPRITE_SMALL_TRAIN_N",
	"SPRITE_SMALL_TRAIN_NE",
	"SPRITE_SMALL_TRAIN_E",
	"SPRITE_SMALL_TRAIN_SE",
	"SPRITE_SMALL_TRAIN_S",
	"SPRITE_SMALL_NESSIE",
	"SPRITE_SMALL_SAILBOAT_NE",
	"SPRITE_SMALL_SAILBOAT_SE",
	"SPRITE_SMALL_POLICE_DISPATCH",
	"SPRITE_SMALL_FIREDEPT_DISPATCH",
	"SPRITE_SMALL_MILITARY_DISPATCH",
	"SPRITE_SMALL_MONSTERSPACERAY",
	"SPRITE_SMALL_POWEROUTAGEINDICATOR",
	"SPRITE_SMALL_EXPLOSION1",
	"SPRITE_SMALL_EXPLOSION2",
	"SPRITE_SMALL_EXPLOSION3",
	"SPRITE_SMALL_BULLDOZER_NE",
	"SPRITE_SMALL_BULLDOZER_SE",
	"SPRITE_SMALL_DUSTCLOUD1",
	"SPRITE_SMALL_DUSTCLOUD2",
	"SPRITE_SMALL_DUSTCLOUD3",
	"SPRITE_SMALL_DUSTCLOUD4",
	"SPRITE_SMALL_FIRE1",
	"SPRITE_SMALL_FIRE2",
	"SPRITE_SMALL_FIRE3",
	"SPRITE_SMALL_FIRE4",
	"SPRITE_SMALL_ROADLIGHTTRAFFIC_RL",
	"SPRITE_SMALL_ROADLIGHTTRAFFIC_TB",
	"SPRITE_SMALL_ROADLIGHTTRAFFIC_HTB",
	"SPRITE_SMALL_ROADLIGHTTRAFFIC_HRL",
	"SPRITE_SMALL_ROADLIGHTTRAFFIC_THB",
	"SPRITE_SMALL_ROADLIGHTTRAFFIC_RHL",
	"SPRITE_SMALL_ROADLIGHTTRAFFIC_RB",
	"SPRITE_SMALL_ROADLIGHTTRAFFIC_BL",
	"SPRITE_SMALL_ROADLIGHTTRAFFIC_TL",
	"SPRITE_SMALL_ROADLIGHTTRAFFIC_TR",
	"SPRITE_SMALL_HIGHWAYLIGHTTRAFFIC_RL",
	"SPRITE_SMALL_HIGHWAYLIGHTTRAFFIC_TB",
	"SPRITE_SMALL_CAUSEWAYLIGHTTRAFFIC_RL",
	"SPRITE_SMALL_CAUSEWAYLIGHTTRAFFIC_TB",
	"SPRITE_SMALL_HIGHWAYONRAMPLIGHTTRAFFIC_RB",
	"SPRITE_SMALL_HIGHWAYONRAMPLIGHTTRAFFIC_TR",
	"SPRITE_SMALL_HIGHWAYONRAMPLIGHTTRAFFIC_RT",
	"SPRITE_SMALL_HIGHWAYONRAMPLIGHTTRAFFIC_BL",
	"SPRITE_SMALL_HIGHWAYLIGHTTRAFFIC_HTB",
	"SPRITE_SMALL_HIGHWAYLIGHTTRAFFIC_HRL",
	"SPRITE_SMALL_HIGHWAYLIGHTTRAFFIC_THB",
	"SPRITE_SMALL_HIGHWAYLIGHTTRAFFIC_RHL",
	"SPRITE_SMALL_HIGHWAYLIGHTTRAFFIC_RB",
	"SPRITE_SMALL_HIGHWAYLIGHTTRAFFIC_BL",
	"SPRITE_SMALL_HIGHWAYLIGHTTRAFFIC_TL",
	"SPRITE_SMALL_HIGHWAYLIGHTTRAFFIC_TR",
	"SPRITE_SMALL_HIGHWAYINTERCHANGELIGHTTRAFFIC_TRBL",
	"SPRITE_SMALL_ROADHEAVYTRAFFIC_RL",
	"SPRITE_SMALL_ROADHEAVYTRAFFIC_TB",
	"SPRITE_SMALL_ROADHEAVYTRAFFIC_HTB",
	"SPRITE_SMALL_ROADHEAVYTRAFFIC_HRL",
	"SPRITE_SMALL_ROADHEAVYTRAFFIC_THB",
	"SPRITE_SMALL_ROADHEAVYTRAFFIC_RHL",
	"SPRITE_SMALL_ROADHEAVYTRAFFIC_RB",
	"SPRITE_SMALL_ROADHEAVYTRAFFIC_BL",
	"SPRITE_SMALL_ROADHEAVYTRAFFIC_TL",
	"SPRITE_SMALL_ROADHEAVYTRAFFIC_TR",
	"SPRITE_SMALL_HIGHWAYHEAVYTRAFFIC_RL",
	"SPRITE_SMALL_HIGHWAYHEAVYTRAFFIC_TB",
	"SPRITE_SMALL_CAUSEWAYHEAVYTRAFFIC_RL",
	"SPRITE_SMALL_CAUSEWAYHEAVYTRAFFIC_TB",
	"SPRITE_SMALL_HIGHWAYHEAVYTRAFFIC_HTB",
	"SPRITE_SMALL_HIGHWAYHEAVYTRAFFIC_HRL",
	"SPRITE_SMALL_HIGHWAYHEAVYTRAFFIC_THB",
	"SPRITE_SMALL_HIGHWAYHEAVYTRAFFIC_RHL",
	"SPRITE_SMALL_HIGHWAYHEAVYTRAFFIC_RB",
	"SPRITE_SMALL_HIGHWAYHEAVYTRAFFIC_BL",
	"SPRITE_SMALL_HIGHWAYHEAVYTRAFFIC_TL",
	"SPRITE_SMALL_HIGHWAYHEAVYTRAFFIC_TR",
	"SPRITE_SMALL_HIGHWAYHEAVYTRAFFIC_TRBL",
	"SPRITE_SMALL_PIPEWATERED_RL",
	"SPRITE_SMALL_PIPEWATERED_TB",
	"SPRITE_SMALL_PIPEWATERED_HTB",
	"SPRITE_SMALL_PIPEWATERED_HRL",
	"SPRITE_SMALL_PIPEWATERED_THB",
	"SPRITE_SMALL_PIPEWATERED_RHL",
	"SPRITE_SMALL_PIPEWATERED_RB",
	"SPRITE_SMALL_PIPEWATERED_BL",
	"SPRITE_SMALL_PIPEWATERED_TL",
	"SPRITE_SMALL_PIPEWATERED_TR",
	"SPRITE_SMALL_PIPEWATERED_TRB",
	"SPRITE_SMALL_PIPEWATERED_RBL",
	"SPRITE_SMALL_PIPEWATERED_TBL",
	"SPRITE_SMALL_PIPEWATERED_TRL",
	"SPRITE_SMALL_PIPEWATERED_TRBL",
	"SPRITE_SMALL_SUBWAY_RL_PIPEWATERED_TB",
	"SPRITE_SMALL_SUBWAY_TB_PIPEWATERED_RL",
	"SPRITE_SMALL_BUILDINGPIPEWATERED_TRBL",
	"SPRITE_SMALL_DENSITYOVERLAY1",
	"SPRITE_SMALL_DENSITYOVERLAY2",
	"SPRITE_SMALL_DENSITYOVERLAY3",
	"SPRITE_SMALL_DENSITYOVERLAY4",
	"SPRITE_SMALL_DENSITYOVERLAY5",
	"SPRITE_SMALL_DENSITYOVERLAY6",
	"SPRITE_SMALL_DENSITYOVERLAY7",
	"SPRITE_SMALL_DENSITYOVERLAY8",
	"SPRITE_SMALL_GREENPLUS",
	"SPRITE_SMALL_REDNEGATIVE",
	"SPRITE_SMALL_MONSTERPARTS1",
	"SPRITE_SMALL_MONSTERPARTS2",
	"SPRITE_SMALL_MONSTERPARTS3",
	"SPRITE_SMALL_MONSTERPARTS4",
	"SPRITE_SMALL_MONSTERPARTS5",
	"SPRITE_SMALL_MONSTERPARTS6",
	"SPRITE_SMALL_MONSTERPARTS7",
	"SPRITE_SMALL_MONSTERPARTS8",
	"SPRITE_SMALL_MONSTERPARTS9",
	"SPRITE_SMALL_MONSTERPARTS10",
	"SPRITE_SMALL_MONSTERPARTS11",
	"SPRITE_SMALL_MONSTERPARTS12",
	"SPRITE_SMALL_MONSTERPARTS13",
	"SPRITE_SMALL_MONSTERPARTS14",
	"SPRITE_SMALL_FLOODWATER",
	"SPRITE_SMALL_RIOTERS1",
	"SPRITE_SMALL_RIOTERS2",
	"SPRITE_SMALL_MAXISMAN",
	"SPRITE_SMALL_DUSTCLOUD",
	"SPRITE_SMALL_TORNADO1",
	"SPRITE_SMALL_TORNADO2",
	"SPRITE_SMALL_TORNADO3",

	"SPRITE_MEDIUM_CLEAR",
	"SPRITE_MEDIUM_RUBBLE1",
	"SPRITE_MEDIUM_RUBBLE2",
	"SPRITE_MEDIUM_RUBBLE3",
	"SPRITE_MEDIUM_RUBBLE4",
	"SPRITE_MEDIUM_RADIOACTIVITY",
	"SPRITE_MEDIUM_TREES1",
	"SPRITE_MEDIUM_TREES2",
	"SPRITE_MEDIUM_TREES3",
	"SPRITE_MEDIUM_TREES4",
	"SPRITE_MEDIUM_TREES5",
	"SPRITE_MEDIUM_TREES6",
	"SPRITE_MEDIUM_TREES7",
	"SPRITE_MEDIUM_SMALLPARK",
	"SPRITE_MEDIUM_POWERLINES_LR",
	"SPRITE_MEDIUM_POWERLINES_TB",
	"SPRITE_MEDIUM_POWERLINES_HTB",
	"SPRITE_MEDIUM_POWERLINES_LHR",
	"SPRITE_MEDIUM_POWERLINES_THB",
	"SPRITE_MEDIUM_POWERLINES_HLR",
	"SPRITE_MEDIUM_POWERLINES_BR",
	"SPRITE_MEDIUM_POWERLINES_BL",
	"SPRITE_MEDIUM_POWERLINES_TL",
	"SPRITE_MEDIUM_POWERLINES_TR",
	"SPRITE_MEDIUM_POWERLINES_RTB",
	"SPRITE_MEDIUM_POWERLINES_LBR",
	"SPRITE_MEDIUM_POWERLINES_TLB",
	"SPRITE_MEDIUM_POWERLINES_LTR",
	"SPRITE_MEDIUM_POWERLINES_LTBR",
	"SPRITE_MEDIUM_ROAD_LR",
	"SPRITE_MEDIUM_ROAD_TB",
	"SPRITE_MEDIUM_ROAD_HTB",
	"SPRITE_MEDIUM_ROAD_LHR",
	"SPRITE_MEDIUM_ROAD_THB",
	"SPRITE_MEDIUM_ROAD_HLR",
	"SPRITE_MEDIUM_ROAD_BR",
	"SPRITE_MEDIUM_ROAD_BL",
	"SPRITE_MEDIUM_ROAD_TL",
	"SPRITE_MEDIUM_ROAD_TR",
	"SPRITE_MEDIUM_ROAD_RTB",
	"SPRITE_MEDIUM_ROAD_LBR",
	"SPRITE_MEDIUM_ROAD_TLB",
	"SPRITE_MEDIUM_ROAD_LTR",
	"SPRITE_MEDIUM_ROAD_LTBR",
	"SPRITE_MEDIUM_RAIL_LR",
	"SPRITE_MEDIUM_RAIL_TB",
	"SPRITE_MEDIUM_RAIL_HTB",
	"SPRITE_MEDIUM_RAIL_LHR",
	"SPRITE_MEDIUM_RAIL_THB",
	"SPRITE_MEDIUM_RAIL_HLR",
	"SPRITE_MEDIUM_RAIL_BR",
	"SPRITE_MEDIUM_RAIL_BL",
	"SPRITE_MEDIUM_RAIL_TL",
	"SPRITE_MEDIUM_RAIL_TR",
	"SPRITE_MEDIUM_RAIL_RTB",
	"SPRITE_MEDIUM_RAIL_LBR",
	"SPRITE_MEDIUM_RAIL_TLB",
	"SPRITE_MEDIUM_RAIL_LTR",
	"SPRITE_MEDIUM_RAIL_LTBR",
	"SPRITE_MEDIUM_RAIL_HHTB",
	"SPRITE_MEDIUM_RAIL_LHHR",
	"SPRITE_MEDIUM_RAIL_THHB",
	"SPRITE_MEDIUM_RAIL_HHLR",
	"SPRITE_MEDIUM_TUNNEL_T",
	"SPRITE_MEDIUM_TUNNEL_R",
	"SPRITE_MEDIUM_TUNNEL_B",
	"SPRITE_MEDIUM_TUNNEL_L",
	"SPRITE_MEDIUM_CROSSOVER_POWERTB_ROADLR",
	"SPRITE_MEDIUM_CROSSOVER_POWERLR_ROADTB",
	"SPRITE_MEDIUM_CROSSOVER_ROADLR_RAILTB",
	"SPRITE_MEDIUM_CROSSOVER_ROADTB_RAILLR",
	"SPRITE_MEDIUM_CROSSOVER_POWERTB_RAILLR",
	"SPRITE_MEDIUM_CROSSOVER_POWERLR_RAILTB",
	"SPRITE_MEDIUM_HIGHWAY_LR",
	"SPRITE_MEDIUM_HIGHWAY_TB",
	"SPRITE_MEDIUM_CROSSOVER_HIGHWAYLR_ROADTB",
	"SPRITE_MEDIUM_CROSSOVER_HIGHWAYTB_ROADLR",
	"SPRITE_MEDIUM_CROSSOVER_HIGHWAYLR_RAILTB",
	"SPRITE_MEDIUM_CROSSOVER_HIGHWAYTB_RAILLR",
	"SPRITE_MEDIUM_CROSSOVER_HIGHWAYLR_POWERTB",
	"SPRITE_MEDIUM_CROSSOVER_HIGHWAYTB_POWERLR",
	"SPRITE_MEDIUM_SUSPENSION_BRIDGE_START_B",
	"SPRITE_MEDIUM_SUSPENSION_BRIDGE_MIDDLE_B",
	"SPRITE_MEDIUM_SUSPENSION_BRIDGE_CENTER_B",
	"SPRITE_MEDIUM_SUSPENSION_BRIDGE_MIDDLE_T",
	"SPRITE_MEDIUM_SUSPENSION_BRIDGE_END_T",
	"SPRITE_MEDIUM_RAISING_BRIDGE_TOWER",
	"SPRITE_MEDIUM_CAUSEWAY_PYLON",
	"SPRITE_MEDIUM_RAISING_BRIDGE_LOWERED",
	"SPRITE_MEDIUM_RAISING_BRIDGE_RAISED",
	"SPRITE_MEDIUM_RAIL_BRIDGE_PYLON",
	"SPRITE_MEDIUM_RAIL_BRIDGE",
	"SPRITE_MEDIUM_ELEVATED_POWERLINES",
	"SPRITE_MEDIUM_ONRAMP_TL",
	"SPRITE_MEDIUM_ONRAMP_TR",
	"SPRITE_MEDIUM_ONRAMP_BL",
	"SPRITE_MEDIUM_ONRAMP_BR",
	"SPRITE_MEDIUM_HIGHWAY_HTB",
	"SPRITE_MEDIUM_HIGHWAY_LHR",
	"SPRITE_MEDIUM_HIGHWAY_THB",
	"SPRITE_MEDIUM_HIGHWAY_HLR",
	"SPRITE_MEDIUM_HIGHWAY_BR",
	"SPRITE_MEDIUM_HIGHWAY_BL",
	"SPRITE_MEDIUM_HIGHWAY_TL",
	"SPRITE_MEDIUM_HIGHWAY_TR",
	"SPRITE_MEDIUM_HIGHWAY_LTBR",
	"SPRITE_MEDIUM_REINFORCED_BRIDGE_PYLON",
	"SPRITE_MEDIUM_REINFORCED_BRIDGE",
	"SPRITE_MEDIUM_SUBTORAIL_T",
	"SPRITE_MEDIUM_SUBTORAIL_R",
	"SPRITE_MEDIUM_SUBTORAIL_B",
	"SPRITE_MEDIUM_SUBTORAIL_L",
	"SPRITE_MEDIUM_RESIDENTIAL_1X1_LOWERCLASSHOMES1",
	"SPRITE_MEDIUM_RESIDENTIAL_1X1_LOWERCLASSHOMES2",
	"SPRITE_MEDIUM_RESIDENTIAL_1X1_LOWERCLASSHOMES3",
	"SPRITE_MEDIUM_RESIDENTIAL_1X1_LOWERCLASSHOMES4",
	"SPRITE_MEDIUM_RESIDENTIAL_1X1_MIDDLECLASSHOMES1",
	"SPRITE_MEDIUM_RESIDENTIAL_1X1_MIDDLECLASSHOMES2",
	"SPRITE_MEDIUM_RESIDENTIAL_1X1_MIDDLECLASSHOMES3",
	"SPRITE_MEDIUM_RESIDENTIAL_1X1_MIDDLECLASSHOMES4",
	"SPRITE_MEDIUM_RESIDENTIAL_1X1_UPPERCLASSHOMES1",
	"SPRITE_MEDIUM_RESIDENTIAL_1X1_UPPERCLASSHOMES2",
	"SPRITE_MEDIUM_RESIDENTIAL_1X1_UPPERCLASSHOMES3",
	"SPRITE_MEDIUM_RESIDENTIAL_1X1_UPPERCLASSHOMES4",
	"SPRITE_MEDIUM_COMMERCIAL_1X1_GASSTATION1",
	"SPRITE_MEDIUM_COMMERCIAL_1X1_BEDANDBREAKFAST",
	"SPRITE_MEDIUM_COMMERCIAL_1X1_CONVENIENCESTORE",
	"SPRITE_MEDIUM_COMMERCIAL_1X1_GASSTATION2",
	"SPRITE_MEDIUM_COMMERCIAL_1X1_SMALLOFFICEBUILDING1",
	"SPRITE_MEDIUM_COMMERCIAL_1X1_SMALLOFFICEBUILDING2",
	"SPRITE_MEDIUM_COMMERCIAL_1X1_WAREHOUSE",
	"SPRITE_MEDIUM_COMMERCIAL_1X1_TOYSTORE",
	"SPRITE_MEDIUM_INDUSTRIAL_1X1_SMALLWAREHOUSE1",
	"SPRITE_MEDIUM_INDUSTRIAL_1X1_CHEMICALSTORAGE",
	"SPRITE_MEDIUM_INDUSTRIAL_1X1_SMALLWAREHOUSE2",
	"SPRITE_MEDIUM_INDUSTRIAL_1X1_SUBSTATION",
	"SPRITE_MEDIUM_MISC_1X1_CONSTRUCTION1",
	"SPRITE_MEDIUM_MISC_1X1_CONSTRUCTION2",
	"SPRITE_MEDIUM_MISC_1X1_ABANDONED1",
	"SPRITE_MEDIUM_MISC_1X1_ABANDONED2",
	"SPRITE_MEDIUM_RESIDENTIAL_2X2_SMALLAPARTMENTS1",
	"SPRITE_MEDIUM_RESIDENTIAL_2X2_SMALLAPARTMENTS2",
	"SPRITE_MEDIUM_RESIDENTIAL_2X2_SMALLAPARTMENTS3",
	"SPRITE_MEDIUM_RESIDENTIAL_2X2_MEDIUMAPARTMENTS1",
	"SPRITE_MEDIUM_RESIDENTIAL_2X2_MEDIUMAPARTMENTS2",
	"SPRITE_MEDIUM_RESIDENTIAL_2X2_MEDIUMCONDOS1",
	"SPRITE_MEDIUM_RESIDENTIAL_2X2_MEDIUMCONDOS2",
	"SPRITE_MEDIUM_RESIDENTIAL_2X2_MEDIUMCONDOS3",
	"SPRITE_MEDIUM_COMMERCIAL_2X2_SHOPPINGCENTER",
	"SPRITE_MEDIUM_COMMERCIAL_2X2_GROCERYSTORE",
	"SPRITE_MEDIUM_COMMERCIAL_2X2_MEDIUMOFFICE1",
	"SPRITE_MEDIUM_COMMERCIAL_2X2_RESORTHOTEL",
	"SPRITE_MEDIUM_COMMERCIAL_2X2_MEDIUMOFFICE2",
	"SPRITE_MEDIUM_COMMERCIAL_2X2_OFFICERETAIL",
	"SPRITE_MEDIUM_COMMERCIAL_2X2_MEDIUMOFFICE3",
	"SPRITE_MEDIUM_COMMERCIAL_2X2_MEDIUMOFFICE4",
	"SPRITE_MEDIUM_COMMERCIAL_2X2_MEDIUMOFFICE5",
	"SPRITE_MEDIUM_COMMERCIAL_2X2_MEDIUMOFFICE6",
	"SPRITE_MEDIUM_INDUSTRIAL_2X2_MEDIUMWAREHOUSE",
	"SPRITE_MEDIUM_INDUSTRIAL_2X2_CHEMICALPROCESSING",
	"SPRITE_MEDIUM_INDUSTRIAL_2X2_FACTORY1",
	"SPRITE_MEDIUM_INDUSTRIAL_2X2_FACTORY2",
	"SPRITE_MEDIUM_INDUSTRIAL_2X2_FACTORY3",
	"SPRITE_MEDIUM_INDUSTRIAL_2X2_FACTORY4",
	"SPRITE_MEDIUM_INDUSTRIAL_2X2_FACTORY5",
	"SPRITE_MEDIUM_INDUSTRIAL_2X2_FACTORY6",
	"SPRITE_MEDIUM_MISC_2X2_CONSTRUCTION1",
	"SPRITE_MEDIUM_MISC_2X2_CONSTRUCTION2",
	"SPRITE_MEDIUM_MISC_2X2_CONSTRUCTION3",
	"SPRITE_MEDIUM_MISC_2X2_CONSTRUCTION4",
	"SPRITE_MEDIUM_MISC_2X2_ABANDONED1",
	"SPRITE_MEDIUM_MISC_2X2_ABANDONED2",
	"SPRITE_MEDIUM_MISC_2X2_ABANDONED3",
	"SPRITE_MEDIUM_MISC_2X2_ABANDONED4",
	"SPRITE_MEDIUM_RESIDENTIAL_3X3_LARGEAPARTMENTS1",
	"SPRITE_MEDIUM_RESIDENTIAL_3X3_LARGEAPARTMENTS2",
	"SPRITE_MEDIUM_RESIDENTIAL_3X3_LARGECONDOS1",
	"SPRITE_MEDIUM_RESIDENTIAL_3X3_LARGECONDOS2",
	"SPRITE_MEDIUM_COMMERCIAL_3X3_OFFICEPARK",
	"SPRITE_MEDIUM_COMMERCIAL_3X3_OFFICETOWER1",
	"SPRITE_MEDIUM_COMMERCIAL_3X3_MINIMALL",
	"SPRITE_MEDIUM_COMMERCIAL_3X3_THEATERSQUARE",
	"SPRITE_MEDIUM_COMMERCIAL_3X3_DRIVEINTHEATER",
	"SPRITE_MEDIUM_COMMERCIAL_3X3_OFFICETOWER2",
	"SPRITE_MEDIUM_COMMERCIAL_3X3_OFFICETOWER3",
	"SPRITE_MEDIUM_COMMERCIAL_3X3_PARKINGLOT",
	"SPRITE_MEDIUM_COMMERCIAL_3X3_HISTORICOFFICE",
	"SPRITE_MEDIUM_COMMERCIAL_3X3_CORPORATEHQ",
	"SPRITE_MEDIUM_INDUSTRIAL_3X3_CHEMICALPROCESSING",
	"SPRITE_MEDIUM_INDUSTRIAL_3X3_LARGEFACTORY",
	"SPRITE_MEDIUM_INDUSTRIAL_3X3_THINGAMAJIG",
	"SPRITE_MEDIUM_INDUSTRIAL_3X3_MEDIUMFACTORY",
	"SPRITE_MEDIUM_INDUSTRIAL_3X3_LARGEWAREHOUSE1",
	"SPRITE_MEDIUM_INDUSTRIAL_3X3_LARGEWAREHOUSE2",
	"SPRITE_MEDIUM_MISC_3X3_CONSTRUCTION1",
	"SPRITE_MEDIUM_MISC_3X3_CONSTRUCTION2",
	"SPRITE_MEDIUM_MISC_3X3_ABANDONED1",
	"SPRITE_MEDIUM_MISC_3X3_ABANDONED2",
	"SPRITE_MEDIUM_POWERPLANT_HYDRO1",
	"SPRITE_MEDIUM_POWERPLANT_HYDRO2",
	"SPRITE_MEDIUM_POWERPLANT_WIND",
	"SPRITE_MEDIUM_POWERPLANT_GAS",
	"SPRITE_MEDIUM_POWERPLANT_OIL",
	"SPRITE_MEDIUM_POWERPLANT_NUCLEAR",
	"SPRITE_MEDIUM_POWERPLANT_SOLAR",
	"SPRITE_MEDIUM_POWERPLANT_MICROWAVE",
	"SPRITE_MEDIUM_POWERPLANT_FUSION",
	"SPRITE_MEDIUM_POWERPLANT_COAL",
	"SPRITE_MEDIUM_SERVICES_CITYHALL",
	"SPRITE_MEDIUM_SERVICES_HOSPITAL",
	"SPRITE_MEDIUM_SERVICES_POLICE",
	"SPRITE_MEDIUM_SERVICES_FIRE",
	"SPRITE_MEDIUM_SERVICES_MUSEUM",
	"SPRITE_MEDIUM_SERVICES_BIGPARK",
	"SPRITE_MEDIUM_SERVICES_SCHOOL",
	"SPRITE_MEDIUM_SERVICES_STADIUM",
	"SPRITE_MEDIUM_SERVICES_PRISON",
	"SPRITE_MEDIUM_SERVICES_COLLEGE",
	"SPRITE_MEDIUM_SERVICES_ZOO",
	"SPRITE_MEDIUM_SERVICES_STATUE",
	"SPRITE_MEDIUM_INFRASTRUCTURE_WATERPUMP",
	"SPRITE_MEDIUM_INFRASTRUCTURE_RUNWAY",
	"SPRITE_MEDIUM_INFRASTRUCTURE_RUNWAYCROSS",
	"SPRITE_MEDIUM_INFRASTRUCTURE_PIER",
	"SPRITE_MEDIUM_INFRASTRUCTURE_CRANE",
	"SPRITE_MEDIUM_INFRASTRUCTURE_CONTROLTOWER_CIV",
	"SPRITE_MEDIUM_MILITARY_CONTROLTOWER",
	"SPRITE_MEDIUM_MILITARY_WAREHOUSE",
	"SPRITE_MEDIUM_INFRASTRUCTURE_BUILDING1",
	"SPRITE_MEDIUM_INFRASTRUCTURE_BUILDING2",
	"SPRITE_MEDIUM_MILITARY_TARMAC",
	"SPRITE_MEDIUM_MILITARY_F15B",
	"SPRITE_MEDIUM_MILITARY_HANGAR1",
	"SPRITE_MEDIUM_INFRASTRUCTURE_SUBWAYSTATION",
	"SPRITE_MEDIUM_MILITARY_RADAR",
	"SPRITE_MEDIUM_INFRASTRUCTURE_WATERTOWER",
	"SPRITE_MEDIUM_INFRASTRUCTURE_BUSDEPOT",
	"SPRITE_MEDIUM_INFRASTRUCTURE_RAILSTATION",
	"SPRITE_MEDIUM_INFRASTRUCTURE_PARKINGLOT",
	"SPRITE_MEDIUM_MILITARY_PARKINGLOT",
	"SPRITE_MEDIUM_MILITARY_LOADINGBAY",
	"SPRITE_MEDIUM_MILITARY_TOPSECRET",
	"SPRITE_MEDIUM_INFRASTRUCTURE_CARGOYARD",
	"SPRITE_MEDIUM_INFRASTRUCTURE_MAYORSHOUSE",
	"SPRITE_MEDIUM_INFRASTRUCTURE_WATERTREATMENT",
	"SPRITE_MEDIUM_INFRASTRUCTURE_LIBRARY",
	"SPRITE_MEDIUM_INFRASTRUCTURE_HANGAR2",
	"SPRITE_MEDIUM_INFRASTRUCTURE_CHURCH",
	"SPRITE_MEDIUM_INFRASTRUCTURE_MARINA",
	"SPRITE_MEDIUM_MILITARY_MISSILESILO",
	"SPRITE_MEDIUM_INFRASTRUCUTRE_DESALINIZATIONPLANT",
	"SPRITE_MEDIUM_ARCOLOGY_PLYMOUTH",
	"SPRITE_MEDIUM_ARCOLOGY_FOREST",
	"SPRITE_MEDIUM_ARCOLOGY_DARCO",
	"SPRITE_MEDIUM_ARCOLOGY_LAUNCH",
	"SPRITE_MEDIUM_OTHER_BRAUNLLAMADOME",
	"SPRITE_MEDIUM_TERRAIN",
	"SPRITE_MEDIUM_TERRAIN_HTB",
	"SPRITE_MEDIUM_TERRAIN_HRL",
	"SPRITE_MEDIUM_TERRAIN_THB",
	"SPRITE_MEDIUM_TERRAIN_RHL",
	"SPRITE_MEDIUM_TERRAIN_HTHRBL",
	"SPRITE_MEDIUM_TERRAIN_THRHBL",
	"SPRITE_MEDIUM_TERRAIN_TRHBHL",
	"SPRITE_MEDIUM_TERRAIN_HTRBHL",
	"SPRITE_MEDIUM_TERRAINSLOPE_HTHRBL",
	"SPRITE_MEDIUM_TERRAINSLOPE_THRHBL",
	"SPRITE_MEDIUM_TERRAINSLOPE_TRHBHL",
	"SPRITE_MEDIUM_TERRAINSLOPE_HTRBHL",
	"SPRITE_MEDIUM_BEDROCK",
	"SPRITE_MEDIUM_WATER_TRBL",
	"SPRITE_MEDIUM_WATER_RBL_TERRAIN_T",
	"SPRITE_MEDIUM_WATER_TBL_TERRAIN_R",
	"SPRITE_MEDIUM_WATER_TRL_TERRAIN_B",
	"SPRITE_MEDIUM_WATER_TRB_TERRAIN_L",
	"SPRITE_MEDIUM_WATER_BL_TERRAIN_TR",
	"SPRITE_MEDIUM_WATER_TL_TERRAIN_RB",
	"SPRITE_MEDIUM_WATER_TR_TERRAIN_BL",
	"SPRITE_MEDIUM_WATER_RB_TERRAIN_TL",
	"SPRITE_MEDIUM_WATER_TRB",
	"SPRITE_MEDIUM_WATER_RBL",
	"SPRITE_MEDIUM_WATER_TBL",
	"SPRITE_MEDIUM_WATER_TRL",
	"SPRITE_MEDIUM_ISOLATEDWATER_TERRAIN_TRBL",
	"SPRITE_MEDIUM_WATERFALL",
	"SPRITE_MEDIUM_WATER_RL_TERRAIN_TB",
	"SPRITE_MEDIUM_WATER_TB_TERRAIN_RL",
	"SPRITE_MEDIUM_WATER_B_TERRAIN_TRL",
	"SPRITE_MEDIUM_WATER_L_TERRAIN_TRB",
	"SPRITE_MEDIUM_WATER_T_TERRAIN_RBL",
	"SPRITE_MEDIUM_WATER_R_TERRAIN_TBL",
	"SPRITE_MEDIUM_LOWDENSITY_RESIDENTIALZONE",
	"SPRITE_MEDIUM_HIGHDENSITY_RESIDENTIALZONE",
	"SPRITE_MEDIUM_LOWDENSITY_COMMERCIALZONE",
	"SPRITE_MEDIUM_HIGHDENSITY_COMMERCIALZONE",
	"SPRITE_MEDIUM_LOWDENSITY_INDUSTRIALZONE",
	"SPRITE_MEDIUM_HIGHDENSITY_INDUSTRIALZONE",
	"SPRITE_MEDIUM_MILITARYZONE",
	"SPRITE_MEDIUM_AIRPORTZONE",
	"SPRITE_MEDIUM_SEAPORTZONE",
	"SPRITE_MEDIUM_GREENTILE",
	"SPRITE_MEDIUM_BLUETILE",
	"SPRITE_MEDIUM_YELLOWTILE",
	"SPRITE_MEDIUM_REDTILE",
	"SPRITE_MEDIUM_GREYTILE",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAIN",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAIN_HTB",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAIN_HRL",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAIN_THB",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAIN_RHL",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAIN_HTHRBL",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAIN_THRHBL",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAIN_TRHBHL",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAIN_HTRBHL",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAINSLOPE_HTHRBL",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAINSLOPE_THRHBL",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAINSLOPE_TRHBHL",
	"SPRITE_MEDIUM_UNDERGROUND_TERRAINSLOPE_HTRBHL",
	"SPRITE_MEDIUM_BEDROCK_OUTLINE",
	"SPRITE_MEDIUM_SUBWAY_LR",
	"SPRITE_MEDIUM_SUBWAY_TB",
	"SPRITE_MEDIUM_SUBWAY_HTB",
	"SPRITE_MEDIUM_SUBWAY_LHR",
	"SPRITE_MEDIUM_SUBWAY_THB",
	"SPRITE_MEDIUM_SUBWAY_HLR",
	"SPRITE_MEDIUM_SUBWAY_BR",
	"SPRITE_MEDIUM_SUBWAY_BL",
	"SPRITE_MEDIUM_SUBWAY_TL",
	"SPRITE_MEDIUM_SUBWAY_TR",
	"SPRITE_MEDIUM_SUBWAY_RTB",
	"SPRITE_MEDIUM_SUBWAY_LBR",
	"SPRITE_MEDIUM_SUBWAY_TLB",
	"SPRITE_MEDIUM_SUBWAY_LTR",
	"SPRITE_MEDIUM_SUBWAY_LTBR",
	"SPRITE_MEDIUM_PIPES_LR",
	"SPRITE_MEDIUM_PIPES_TB",
	"SPRITE_MEDIUM_PIPES_HTB",
	"SPRITE_MEDIUM_PIPES_LHR",
	"SPRITE_MEDIUM_PIPES_THB",
	"SPRITE_MEDIUM_PIPES_HLR",
	"SPRITE_MEDIUM_PIPES_BR",
	"SPRITE_MEDIUM_PIPES_BL",
	"SPRITE_MEDIUM_PIPES_TL",
	"SPRITE_MEDIUM_PIPES_TR",
	"SPRITE_MEDIUM_PIPES_RTB",
	"SPRITE_MEDIUM_PIPES_LBR",
	"SPRITE_MEDIUM_PIPES_TLB",
	"SPRITE_MEDIUM_PIPES_LTR",
	"SPRITE_MEDIUM_PIPES_LTBR",
	"SPRITE_MEDIUM_CROSSOVER_PIPESTB_SUBWAYLR",
	"SPRITE_MEDIUM_CROSSOVER_PIPESLR_SUBWAYTB",
	"SPRITE_MEDIUM_BUILDINGPIPE",
	"SPRITE_MEDIUM_MISSILESILO",
	"SPRITE_MEDIUM_SUBWAYENTRANCE",
	"SPRITE_MEDIUM_GREENOUTLINE",
	"SPRITE_MEDIUM_BLUEOUTLINE",
	"SPRITE_MEDIUM_BROWNOUTLINE",
	"SPRITE_MEDIUM_REDOUTLINE",
	"SPRITE_MEDIUM_GREYOUTLINE",
	"SPRITE_MEDIUM_AIRPLANE_N",
	"SPRITE_MEDIUM_AIRPLANE_NE",
	"SPRITE_MEDIUM_AIRPLANE_E",
	"SPRITE_MEDIUM_AIRPLANE_SE",
	"SPRITE_MEDIUM_AIRPLANE_S",
	"SPRITE_MEDIUM_SIMCOPTER_N",
	"SPRITE_MEDIUM_SIMCOPTER_NE",
	"SPRITE_MEDIUM_SIMCOPTER_E",
	"SPRITE_MEDIUM_SIMCOPTER_SE",
	"SPRITE_MEDIUM_SIMCOPTER_S",
	"SPRITE_MEDIUM_CARGOSHIP_N",
	"SPRITE_MEDIUM_CARGOSHIP_NE",
	"SPRITE_MEDIUM_CARGOSHIP_E",
	"SPRITE_MEDIUM_CARGOSHIP_SE",
	"SPRITE_MEDIUM_CARGOSHIP_S",
	"SPRITE_MEDIUM_TRAIN_N",
	"SPRITE_MEDIUM_TRAIN_NE",
	"SPRITE_MEDIUM_TRAIN_E",
	"SPRITE_MEDIUM_TRAIN_SE",
	"SPRITE_MEDIUM_TRAIN_S",
	"SPRITE_MEDIUM_NESSIE",
	"SPRITE_MEDIUM_SAILBOAT_NE",
	"SPRITE_MEDIUM_SAILBOAT_SE",
	"SPRITE_MEDIUM_POLICE_DISPATCH",
	"SPRITE_MEDIUM_FIREDEPT_DISPATCH",
	"SPRITE_MEDIUM_MILITARY_DISPATCH",
	"SPRITE_MEDIUM_MONSTERSPACERAY",
	"SPRITE_MEDIUM_POWEROUTAGEINDICATOR",
	"SPRITE_MEDIUM_EXPLOSION1",
	"SPRITE_MEDIUM_EXPLOSION2",
	"SPRITE_MEDIUM_EXPLOSION3",
	"SPRITE_MEDIUM_BULLDOZER_NE",
	"SPRITE_MEDIUM_BULLDOZER_SE",
	"SPRITE_MEDIUM_DUSTCLOUD1",
	"SPRITE_MEDIUM_DUSTCLOUD2",
	"SPRITE_MEDIUM_DUSTCLOUD3",
	"SPRITE_MEDIUM_DUSTCLOUD4",
	"SPRITE_MEDIUM_FIRE1",
	"SPRITE_MEDIUM_FIRE2",
	"SPRITE_MEDIUM_FIRE3",
	"SPRITE_MEDIUM_FIRE4",
	"SPRITE_MEDIUM_ROADLIGHTTRAFFIC_RL",
	"SPRITE_MEDIUM_ROADLIGHTTRAFFIC_TB",
	"SPRITE_MEDIUM_ROADLIGHTTRAFFIC_HTB",
	"SPRITE_MEDIUM_ROADLIGHTTRAFFIC_HRL",
	"SPRITE_MEDIUM_ROADLIGHTTRAFFIC_THB",
	"SPRITE_MEDIUM_ROADLIGHTTRAFFIC_RHL",
	"SPRITE_MEDIUM_ROADLIGHTTRAFFIC_RB",
	"SPRITE_MEDIUM_ROADLIGHTTRAFFIC_BL",
	"SPRITE_MEDIUM_ROADLIGHTTRAFFIC_TL",
	"SPRITE_MEDIUM_ROADLIGHTTRAFFIC_TR",
	"SPRITE_MEDIUM_HIGHWAYLIGHTTRAFFIC_RL",
	"SPRITE_MEDIUM_HIGHWAYLIGHTTRAFFIC_TB",
	"SPRITE_MEDIUM_CAUSEWAYLIGHTTRAFFIC_RL",
	"SPRITE_MEDIUM_CAUSEWAYLIGHTTRAFFIC_TB",
	"SPRITE_MEDIUM_HIGHWAYONRAMPLIGHTTRAFFIC_RB",
	"SPRITE_MEDIUM_HIGHWAYONRAMPLIGHTTRAFFIC_TR",
	"SPRITE_MEDIUM_HIGHWAYONRAMPLIGHTTRAFFIC_RT",
	"SPRITE_MEDIUM_HIGHWAYONRAMPLIGHTTRAFFIC_BL",
	"SPRITE_MEDIUM_HIGHWAYLIGHTTRAFFIC_HTB",
	"SPRITE_MEDIUM_HIGHWAYLIGHTTRAFFIC_HRL",
	"SPRITE_MEDIUM_HIGHWAYLIGHTTRAFFIC_THB",
	"SPRITE_MEDIUM_HIGHWAYLIGHTTRAFFIC_RHL",
	"SPRITE_MEDIUM_HIGHWAYLIGHTTRAFFIC_RB",
	"SPRITE_MEDIUM_HIGHWAYLIGHTTRAFFIC_BL",
	"SPRITE_MEDIUM_HIGHWAYLIGHTTRAFFIC_TL",
	"SPRITE_MEDIUM_HIGHWAYLIGHTTRAFFIC_TR",
	"SPRITE_MEDIUM_HIGHWAYINTERCHANGELIGHTTRAFFIC_TRBL",
	"SPRITE_MEDIUM_ROADHEAVYTRAFFIC_RL",
	"SPRITE_MEDIUM_ROADHEAVYTRAFFIC_TB",
	"SPRITE_MEDIUM_ROADHEAVYTRAFFIC_HTB",
	"SPRITE_MEDIUM_ROADHEAVYTRAFFIC_HRL",
	"SPRITE_MEDIUM_ROADHEAVYTRAFFIC_THB",
	"SPRITE_MEDIUM_ROADHEAVYTRAFFIC_RHL",
	"SPRITE_MEDIUM_ROADHEAVYTRAFFIC_RB",
	"SPRITE_MEDIUM_ROADHEAVYTRAFFIC_BL",
	"SPRITE_MEDIUM_ROADHEAVYTRAFFIC_TL",
	"SPRITE_MEDIUM_ROADHEAVYTRAFFIC_TR",
	"SPRITE_MEDIUM_HIGHWAYHEAVYTRAFFIC_RL",
	"SPRITE_MEDIUM_HIGHWAYHEAVYTRAFFIC_TB",
	"SPRITE_MEDIUM_CAUSEWAYHEAVYTRAFFIC_RL",
	"SPRITE_MEDIUM_CAUSEWAYHEAVYTRAFFIC_TB",
	"SPRITE_MEDIUM_HIGHWAYHEAVYTRAFFIC_HTB",
	"SPRITE_MEDIUM_HIGHWAYHEAVYTRAFFIC_HRL",
	"SPRITE_MEDIUM_HIGHWAYHEAVYTRAFFIC_THB",
	"SPRITE_MEDIUM_HIGHWAYHEAVYTRAFFIC_RHL",
	"SPRITE_MEDIUM_HIGHWAYHEAVYTRAFFIC_RB",
	"SPRITE_MEDIUM_HIGHWAYHEAVYTRAFFIC_BL",
	"SPRITE_MEDIUM_HIGHWAYHEAVYTRAFFIC_TL",
	"SPRITE_MEDIUM_HIGHWAYHEAVYTRAFFIC_TR",
	"SPRITE_MEDIUM_HIGHWAYHEAVYTRAFFIC_TRBL",
	"SPRITE_MEDIUM_PIPEWATERED_RL",
	"SPRITE_MEDIUM_PIPEWATERED_TB",
	"SPRITE_MEDIUM_PIPEWATERED_HTB",
	"SPRITE_MEDIUM_PIPEWATERED_HRL",
	"SPRITE_MEDIUM_PIPEWATERED_THB",
	"SPRITE_MEDIUM_PIPEWATERED_RHL",
	"SPRITE_MEDIUM_PIPEWATERED_RB",
	"SPRITE_MEDIUM_PIPEWATERED_BL",
	"SPRITE_MEDIUM_PIPEWATERED_TL",
	"SPRITE_MEDIUM_PIPEWATERED_TR",
	"SPRITE_MEDIUM_PIPEWATERED_TRB",
	"SPRITE_MEDIUM_PIPEWATERED_RBL",
	"SPRITE_MEDIUM_PIPEWATERED_TBL",
	"SPRITE_MEDIUM_PIPEWATERED_TRL",
	"SPRITE_MEDIUM_PIPEWATERED_TRBL",
	"SPRITE_MEDIUM_SUBWAY_RL_PIPEWATERED_TB",
	"SPRITE_MEDIUM_SUBWAY_TB_PIPEWATERED_RL",
	"SPRITE_MEDIUM_BUILDINGPIPEWATERED_TRBL",
	"SPRITE_MEDIUM_DENSITYOVERLAY1",
	"SPRITE_MEDIUM_DENSITYOVERLAY2",
	"SPRITE_MEDIUM_DENSITYOVERLAY3",
	"SPRITE_MEDIUM_DENSITYOVERLAY4",
	"SPRITE_MEDIUM_DENSITYOVERLAY5",
	"SPRITE_MEDIUM_DENSITYOVERLAY6",
	"SPRITE_MEDIUM_DENSITYOVERLAY7",
	"SPRITE_MEDIUM_DENSITYOVERLAY8",
	"SPRITE_MEDIUM_GREENPLUS",
	"SPRITE_MEDIUM_REDNEGATIVE",
	"SPRITE_MEDIUM_MONSTERPARTS1",
	"SPRITE_MEDIUM_MONSTERPARTS2",
	"SPRITE_MEDIUM_MONSTERPARTS3",
	"SPRITE_MEDIUM_MONSTERPARTS4",
	"SPRITE_MEDIUM_MONSTERPARTS5",
	"SPRITE_MEDIUM_MONSTERPARTS6",
	"SPRITE_MEDIUM_MONSTERPARTS7",
	"SPRITE_MEDIUM_MONSTERPARTS8",
	"SPRITE_MEDIUM_MONSTERPARTS9",
	"SPRITE_MEDIUM_MONSTERPARTS10",
	"SPRITE_MEDIUM_MONSTERPARTS11",
	"SPRITE_MEDIUM_MONSTERPARTS12",
	"SPRITE_MEDIUM_MONSTERPARTS13",
	"SPRITE_MEDIUM_MONSTERPARTS14",
	"SPRITE_MEDIUM_FLOODWATER",
	"SPRITE_MEDIUM_RIOTERS1",
	"SPRITE_MEDIUM_RIOTERS2",
	"SPRITE_MEDIUM_MAXISMAN",
	"SPRITE_MEDIUM_DUSTCLOUD",
	"SPRITE_MEDIUM_TORNADO1",
	"SPRITE_MEDIUM_TORNADO2",
	"SPRITE_MEDIUM_TORNADO3",

	"SPRITE_LARGE_CLEAR",
	"SPRITE_LARGE_RUBBLE1",
	"SPRITE_LARGE_RUBBLE2",
	"SPRITE_LARGE_RUBBLE3",
	"SPRITE_LARGE_RUBBLE4",
	"SPRITE_LARGE_RADIOACTIVITY",
	"SPRITE_LARGE_TREES1",
	"SPRITE_LARGE_TREES2",
	"SPRITE_LARGE_TREES3",
	"SPRITE_LARGE_TREES4",
	"SPRITE_LARGE_TREES5",
	"SPRITE_LARGE_TREES6",
	"SPRITE_LARGE_TREES7",
	"SPRITE_LARGE_SMALLPARK",
	"SPRITE_LARGE_POWERLINES_LR",
	"SPRITE_LARGE_POWERLINES_TB",
	"SPRITE_LARGE_POWERLINES_HTB",
	"SPRITE_LARGE_POWERLINES_LHR",
	"SPRITE_LARGE_POWERLINES_THB",
	"SPRITE_LARGE_POWERLINES_HLR",
	"SPRITE_LARGE_POWERLINES_BR",
	"SPRITE_LARGE_POWERLINES_BL",
	"SPRITE_LARGE_POWERLINES_TL",
	"SPRITE_LARGE_POWERLINES_TR",
	"SPRITE_LARGE_POWERLINES_RTB",
	"SPRITE_LARGE_POWERLINES_LBR",
	"SPRITE_LARGE_POWERLINES_TLB",
	"SPRITE_LARGE_POWERLINES_LTR",
	"SPRITE_LARGE_POWERLINES_LTBR",
	"SPRITE_LARGE_ROAD_LR",
	"SPRITE_LARGE_ROAD_TB",
	"SPRITE_LARGE_ROAD_HTB",
	"SPRITE_LARGE_ROAD_LHR",
	"SPRITE_LARGE_ROAD_THB",
	"SPRITE_LARGE_ROAD_HLR",
	"SPRITE_LARGE_ROAD_BR",
	"SPRITE_LARGE_ROAD_BL",
	"SPRITE_LARGE_ROAD_TL",
	"SPRITE_LARGE_ROAD_TR",
	"SPRITE_LARGE_ROAD_RTB",
	"SPRITE_LARGE_ROAD_LBR",
	"SPRITE_LARGE_ROAD_TLB",
	"SPRITE_LARGE_ROAD_LTR",
	"SPRITE_LARGE_ROAD_LTBR",
	"SPRITE_LARGE_RAIL_LR",
	"SPRITE_LARGE_RAIL_TB",
	"SPRITE_LARGE_RAIL_HTB",
	"SPRITE_LARGE_RAIL_LHR",
	"SPRITE_LARGE_RAIL_THB",
	"SPRITE_LARGE_RAIL_HLR",
	"SPRITE_LARGE_RAIL_BR",
	"SPRITE_LARGE_RAIL_BL",
	"SPRITE_LARGE_RAIL_TL",
	"SPRITE_LARGE_RAIL_TR",
	"SPRITE_LARGE_RAIL_RTB",
	"SPRITE_LARGE_RAIL_LBR",
	"SPRITE_LARGE_RAIL_TLB",
	"SPRITE_LARGE_RAIL_LTR",
	"SPRITE_LARGE_RAIL_LTBR",
	"SPRITE_LARGE_RAIL_HHTB",
	"SPRITE_LARGE_RAIL_LHHR",
	"SPRITE_LARGE_RAIL_THHB",
	"SPRITE_LARGE_RAIL_HHLR",
	"SPRITE_LARGE_TUNNEL_T",
	"SPRITE_LARGE_TUNNEL_R",
	"SPRITE_LARGE_TUNNEL_B",
	"SPRITE_LARGE_TUNNEL_L",
	"SPRITE_LARGE_CROSSOVER_POWERTB_ROADLR",
	"SPRITE_LARGE_CROSSOVER_POWERLR_ROADTB",
	"SPRITE_LARGE_CROSSOVER_ROADLR_RAILTB",
	"SPRITE_LARGE_CROSSOVER_ROADTB_RAILLR",
	"SPRITE_LARGE_CROSSOVER_POWERTB_RAILLR",
	"SPRITE_LARGE_CROSSOVER_POWERLR_RAILTB",
	"SPRITE_LARGE_HIGHWAY_LR",
	"SPRITE_LARGE_HIGHWAY_TB",
	"SPRITE_LARGE_CROSSOVER_HIGHWAYLR_ROADTB",
	"SPRITE_LARGE_CROSSOVER_HIGHWAYTB_ROADLR",
	"SPRITE_LARGE_CROSSOVER_HIGHWAYLR_RAILTB",
	"SPRITE_LARGE_CROSSOVER_HIGHWAYTB_RAILLR",
	"SPRITE_LARGE_CROSSOVER_HIGHWAYLR_POWERTB",
	"SPRITE_LARGE_CROSSOVER_HIGHWAYTB_POWERLR",
	"SPRITE_LARGE_SUSPENSION_BRIDGE_START_B",
	"SPRITE_LARGE_SUSPENSION_BRIDGE_MIDDLE_B",
	"SPRITE_LARGE_SUSPENSION_BRIDGE_CENTER_B",
	"SPRITE_LARGE_SUSPENSION_BRIDGE_MIDDLE_T",
	"SPRITE_LARGE_SUSPENSION_BRIDGE_END_T",
	"SPRITE_LARGE_RAISING_BRIDGE_TOWER",
	"SPRITE_LARGE_CAUSEWAY_PYLON",
	"SPRITE_LARGE_RAISING_BRIDGE_LOWERED",
	"SPRITE_LARGE_RAISING_BRIDGE_RAISED",
	"SPRITE_LARGE_RAIL_BRIDGE_PYLON",
	"SPRITE_LARGE_RAIL_BRIDGE",
	"SPRITE_LARGE_ELEVATED_POWERLINES",
	"SPRITE_LARGE_ONRAMP_TL",
	"SPRITE_LARGE_ONRAMP_TR",
	"SPRITE_LARGE_ONRAMP_BL",
	"SPRITE_LARGE_ONRAMP_BR",
	"SPRITE_LARGE_HIGHWAY_HTB",
	"SPRITE_LARGE_HIGHWAY_LHR",
	"SPRITE_LARGE_HIGHWAY_THB",
	"SPRITE_LARGE_HIGHWAY_HLR",
	"SPRITE_LARGE_HIGHWAY_BR",
	"SPRITE_LARGE_HIGHWAY_BL",
	"SPRITE_LARGE_HIGHWAY_TL",
	"SPRITE_LARGE_HIGHWAY_TR",
	"SPRITE_LARGE_HIGHWAY_LTBR",
	"SPRITE_LARGE_REINFORCED_BRIDGE_PYLON",
	"SPRITE_LARGE_REINFORCED_BRIDGE",
	"SPRITE_LARGE_SUBTORAIL_T",
	"SPRITE_LARGE_SUBTORAIL_R",
	"SPRITE_LARGE_SUBTORAIL_B",
	"SPRITE_LARGE_SUBTORAIL_L",
	"SPRITE_LARGE_RESIDENTIAL_1X1_LOWERCLASSHOMES1",
	"SPRITE_LARGE_RESIDENTIAL_1X1_LOWERCLASSHOMES2",
	"SPRITE_LARGE_RESIDENTIAL_1X1_LOWERCLASSHOMES3",
	"SPRITE_LARGE_RESIDENTIAL_1X1_LOWERCLASSHOMES4",
	"SPRITE_LARGE_RESIDENTIAL_1X1_MIDDLECLASSHOMES1",
	"SPRITE_LARGE_RESIDENTIAL_1X1_MIDDLECLASSHOMES2",
	"SPRITE_LARGE_RESIDENTIAL_1X1_MIDDLECLASSHOMES3",
	"SPRITE_LARGE_RESIDENTIAL_1X1_MIDDLECLASSHOMES4",
	"SPRITE_LARGE_RESIDENTIAL_1X1_UPPERCLASSHOMES1",
	"SPRITE_LARGE_RESIDENTIAL_1X1_UPPERCLASSHOMES2",
	"SPRITE_LARGE_RESIDENTIAL_1X1_UPPERCLASSHOMES3",
	"SPRITE_LARGE_RESIDENTIAL_1X1_UPPERCLASSHOMES4",
	"SPRITE_LARGE_COMMERCIAL_1X1_GASSTATION1",
	"SPRITE_LARGE_COMMERCIAL_1X1_BEDANDBREAKFAST",
	"SPRITE_LARGE_COMMERCIAL_1X1_CONVENIENCESTORE",
	"SPRITE_LARGE_COMMERCIAL_1X1_GASSTATION2",
	"SPRITE_LARGE_COMMERCIAL_1X1_SMALLOFFICEBUILDING1",
	"SPRITE_LARGE_COMMERCIAL_1X1_SMALLOFFICEBUILDING2",
	"SPRITE_LARGE_COMMERCIAL_1X1_WAREHOUSE",
	"SPRITE_LARGE_COMMERCIAL_1X1_TOYSTORE",
	"SPRITE_LARGE_INDUSTRIAL_1X1_SMALLWAREHOUSE1",
	"SPRITE_LARGE_INDUSTRIAL_1X1_CHEMICALSTORAGE",
	"SPRITE_LARGE_INDUSTRIAL_1X1_SMALLWAREHOUSE2",
	"SPRITE_LARGE_INDUSTRIAL_1X1_SUBSTATION",
	"SPRITE_LARGE_MISC_1X1_CONSTRUCTION1",
	"SPRITE_LARGE_MISC_1X1_CONSTRUCTION2",
	"SPRITE_LARGE_MISC_1X1_ABANDONED1",
	"SPRITE_LARGE_MISC_1X1_ABANDONED2",
	"SPRITE_LARGE_RESIDENTIAL_2X2_SMALLAPARTMENTS1",
	"SPRITE_LARGE_RESIDENTIAL_2X2_SMALLAPARTMENTS2",
	"SPRITE_LARGE_RESIDENTIAL_2X2_SMALLAPARTMENTS3",
	"SPRITE_LARGE_RESIDENTIAL_2X2_MEDIUMAPARTMENTS1",
	"SPRITE_LARGE_RESIDENTIAL_2X2_MEDIUMAPARTMENTS2",
	"SPRITE_LARGE_RESIDENTIAL_2X2_MEDIUMCONDOS1",
	"SPRITE_LARGE_RESIDENTIAL_2X2_MEDIUMCONDOS2",
	"SPRITE_LARGE_RESIDENTIAL_2X2_MEDIUMCONDOS3",
	"SPRITE_LARGE_COMMERCIAL_2X2_SHOPPINGCENTER",
	"SPRITE_LARGE_COMMERCIAL_2X2_GROCERYSTORE",
	"SPRITE_LARGE_COMMERCIAL_2X2_MEDIUMOFFICE1",
	"SPRITE_LARGE_COMMERCIAL_2X2_RESORTHOTEL",
	"SPRITE_LARGE_COMMERCIAL_2X2_MEDIUMOFFICE2",
	"SPRITE_LARGE_COMMERCIAL_2X2_OFFICERETAIL",
	"SPRITE_LARGE_COMMERCIAL_2X2_MEDIUMOFFICE3",
	"SPRITE_LARGE_COMMERCIAL_2X2_MEDIUMOFFICE4",
	"SPRITE_LARGE_COMMERCIAL_2X2_MEDIUMOFFICE5",
	"SPRITE_LARGE_COMMERCIAL_2X2_MEDIUMOFFICE6",
	"SPRITE_LARGE_INDUSTRIAL_2X2_MEDIUMWAREHOUSE",
	"SPRITE_LARGE_INDUSTRIAL_2X2_CHEMICALPROCESSING",
	"SPRITE_LARGE_INDUSTRIAL_2X2_FACTORY1",
	"SPRITE_LARGE_INDUSTRIAL_2X2_FACTORY2",
	"SPRITE_LARGE_INDUSTRIAL_2X2_FACTORY3",
	"SPRITE_LARGE_INDUSTRIAL_2X2_FACTORY4",
	"SPRITE_LARGE_INDUSTRIAL_2X2_FACTORY5",
	"SPRITE_LARGE_INDUSTRIAL_2X2_FACTORY6",
	"SPRITE_LARGE_MISC_2X2_CONSTRUCTION1",
	"SPRITE_LARGE_MISC_2X2_CONSTRUCTION2",
	"SPRITE_LARGE_MISC_2X2_CONSTRUCTION3",
	"SPRITE_LARGE_MISC_2X2_CONSTRUCTION4",
	"SPRITE_LARGE_MISC_2X2_ABANDONED1",
	"SPRITE_LARGE_MISC_2X2_ABANDONED2",
	"SPRITE_LARGE_MISC_2X2_ABANDONED3",
	"SPRITE_LARGE_MISC_2X2_ABANDONED4",
	"SPRITE_LARGE_RESIDENTIAL_3X3_LARGEAPARTMENTS1",
	"SPRITE_LARGE_RESIDENTIAL_3X3_LARGEAPARTMENTS2",
	"SPRITE_LARGE_RESIDENTIAL_3X3_LARGECONDOS1",
	"SPRITE_LARGE_RESIDENTIAL_3X3_LARGECONDOS2",
	"SPRITE_LARGE_COMMERCIAL_3X3_OFFICEPARK",
	"SPRITE_LARGE_COMMERCIAL_3X3_OFFICETOWER1",
	"SPRITE_LARGE_COMMERCIAL_3X3_MINIMALL",
	"SPRITE_LARGE_COMMERCIAL_3X3_THEATERSQUARE",
	"SPRITE_LARGE_COMMERCIAL_3X3_DRIVEINTHEATER",
	"SPRITE_LARGE_COMMERCIAL_3X3_OFFICETOWER2",
	"SPRITE_LARGE_COMMERCIAL_3X3_OFFICETOWER3",
	"SPRITE_LARGE_COMMERCIAL_3X3_PARKINGLOT",
	"SPRITE_LARGE_COMMERCIAL_3X3_HISTORICOFFICE",
	"SPRITE_LARGE_COMMERCIAL_3X3_CORPORATEHQ",
	"SPRITE_LARGE_INDUSTRIAL_3X3_CHEMICALPROCESSING",
	"SPRITE_LARGE_INDUSTRIAL_3X3_LARGEFACTORY",
	"SPRITE_LARGE_INDUSTRIAL_3X3_THINGAMAJIG",
	"SPRITE_LARGE_INDUSTRIAL_3X3_MEDIUMFACTORY",
	"SPRITE_LARGE_INDUSTRIAL_3X3_LARGEWAREHOUSE1",
	"SPRITE_LARGE_INDUSTRIAL_3X3_LARGEWAREHOUSE2",
	"SPRITE_LARGE_MISC_3X3_CONSTRUCTION1",
	"SPRITE_LARGE_MISC_3X3_CONSTRUCTION2",
	"SPRITE_LARGE_MISC_3X3_ABANDONED1",
	"SPRITE_LARGE_MISC_3X3_ABANDONED2",
	"SPRITE_LARGE_POWERPLANT_HYDRO1",
	"SPRITE_LARGE_POWERPLANT_HYDRO2",
	"SPRITE_LARGE_POWERPLANT_WIND",
	"SPRITE_LARGE_POWERPLANT_GAS",
	"SPRITE_LARGE_POWERPLANT_OIL",
	"SPRITE_LARGE_POWERPLANT_NUCLEAR",
	"SPRITE_LARGE_POWERPLANT_SOLAR",
	"SPRITE_LARGE_POWERPLANT_MICROWAVE",
	"SPRITE_LARGE_POWERPLANT_FUSION",
	"SPRITE_LARGE_POWERPLANT_COAL",
	"SPRITE_LARGE_SERVICES_CITYHALL",
	"SPRITE_LARGE_SERVICES_HOSPITAL",
	"SPRITE_LARGE_SERVICES_POLICE",
	"SPRITE_LARGE_SERVICES_FIRE",
	"SPRITE_LARGE_SERVICES_MUSEUM",
	"SPRITE_LARGE_SERVICES_BIGPARK",
	"SPRITE_LARGE_SERVICES_SCHOOL",
	"SPRITE_LARGE_SERVICES_STADIUM",
	"SPRITE_LARGE_SERVICES_PRISON",
	"SPRITE_LARGE_SERVICES_COLLEGE",
	"SPRITE_LARGE_SERVICES_ZOO",
	"SPRITE_LARGE_SERVICES_STATUE",
	"SPRITE_LARGE_INFRASTRUCTURE_WATERPUMP",
	"SPRITE_LARGE_INFRASTRUCTURE_RUNWAY",
	"SPRITE_LARGE_INFRASTRUCTURE_RUNWAYCROSS",
	"SPRITE_LARGE_INFRASTRUCTURE_PIER",
	"SPRITE_LARGE_INFRASTRUCTURE_CRANE",
	"SPRITE_LARGE_INFRASTRUCTURE_CONTROLTOWER_CIV",
	"SPRITE_LARGE_MILITARY_CONTROLTOWER",
	"SPRITE_LARGE_MILITARY_WAREHOUSE",
	"SPRITE_LARGE_INFRASTRUCTURE_BUILDING1",
	"SPRITE_LARGE_INFRASTRUCTURE_BUILDING2",
	"SPRITE_LARGE_MILITARY_TARMAC",
	"SPRITE_LARGE_MILITARY_F15B",
	"SPRITE_LARGE_MILITARY_HANGAR1",
	"SPRITE_LARGE_INFRASTRUCTURE_SUBWAYSTATION",
	"SPRITE_LARGE_MILITARY_RADAR",
	"SPRITE_LARGE_INFRASTRUCTURE_WATERTOWER",
	"SPRITE_LARGE_INFRASTRUCTURE_BUSDEPOT",
	"SPRITE_LARGE_INFRASTRUCTURE_RAILSTATION",
	"SPRITE_LARGE_INFRASTRUCTURE_PARKINGLOT",
	"SPRITE_LARGE_MILITARY_PARKINGLOT",
	"SPRITE_LARGE_MILITARY_LOADINGBAY",
	"SPRITE_LARGE_MILITARY_TOPSECRET",
	"SPRITE_LARGE_INFRASTRUCTURE_CARGOYARD",
	"SPRITE_LARGE_INFRASTRUCTURE_MAYORSHOUSE",
	"SPRITE_LARGE_INFRASTRUCTURE_WATERTREATMENT",
	"SPRITE_LARGE_INFRASTRUCTURE_LIBRARY",
	"SPRITE_LARGE_INFRASTRUCTURE_HANGAR2",
	"SPRITE_LARGE_INFRASTRUCTURE_CHURCH",
	"SPRITE_LARGE_INFRASTRUCTURE_MARINA",
	"SPRITE_LARGE_MILITARY_MISSILESILO",
	"SPRITE_LARGE_INFRASTRUCUTRE_DESALINIZATIONPLANT",
	"SPRITE_LARGE_ARCOLOGY_PLYMOUTH",
	"SPRITE_LARGE_ARCOLOGY_FOREST",
	"SPRITE_LARGE_ARCOLOGY_DARCO",
	"SPRITE_LARGE_ARCOLOGY_LAUNCH",
	"SPRITE_LARGE_OTHER_BRAUNLLAMADOME",
	"SPRITE_LARGE_TERRAIN",
	"SPRITE_LARGE_TERRAIN_HTB",
	"SPRITE_LARGE_TERRAIN_HRL",
	"SPRITE_LARGE_TERRAIN_THB",
	"SPRITE_LARGE_TERRAIN_RHL",
	"SPRITE_LARGE_TERRAIN_HTHRBL",
	"SPRITE_LARGE_TERRAIN_THRHBL",
	"SPRITE_LARGE_TERRAIN_TRHBHL",
	"SPRITE_LARGE_TERRAIN_HTRBHL",
	"SPRITE_LARGE_TERRAINSLOPE_HTHRBL",
	"SPRITE_LARGE_TERRAINSLOPE_THRHBL",
	"SPRITE_LARGE_TERRAINSLOPE_TRHBHL",
	"SPRITE_LARGE_TERRAINSLOPE_HTRBHL",
	"SPRITE_LARGE_BEDROCK",
	"SPRITE_LARGE_WATER_TRBL",
	"SPRITE_LARGE_WATER_RBL_TERRAIN_T",
	"SPRITE_LARGE_WATER_TBL_TERRAIN_R",
	"SPRITE_LARGE_WATER_TRL_TERRAIN_B",
	"SPRITE_LARGE_WATER_TRB_TERRAIN_L",
	"SPRITE_LARGE_WATER_BL_TERRAIN_TR",
	"SPRITE_LARGE_WATER_TL_TERRAIN_RB",
	"SPRITE_LARGE_WATER_TR_TERRAIN_BL",
	"SPRITE_LARGE_WATER_RB_TERRAIN_TL",
	"SPRITE_LARGE_WATER_TRB",
	"SPRITE_LARGE_WATER_RBL",
	"SPRITE_LARGE_WATER_TBL",
	"SPRITE_LARGE_WATER_TRL",
	"SPRITE_LARGE_ISOLATEDWATER_TERRAIN_TRBL",
	"SPRITE_LARGE_WATERFALL",
	"SPRITE_LARGE_WATER_RL_TERRAIN_TB",
	"SPRITE_LARGE_WATER_TB_TERRAIN_RL",
	"SPRITE_LARGE_WATER_B_TERRAIN_TRL",
	"SPRITE_LARGE_WATER_L_TERRAIN_TRB",
	"SPRITE_LARGE_WATER_T_TERRAIN_RBL",
	"SPRITE_LARGE_WATER_R_TERRAIN_TBL",
	"SPRITE_LARGE_LOWDENSITY_RESIDENTIALZONE",
	"SPRITE_LARGE_HIGHDENSITY_RESIDENTIALZONE",
	"SPRITE_LARGE_LOWDENSITY_COMMERCIALZONE",
	"SPRITE_LARGE_HIGHDENSITY_COMMERCIALZONE",
	"SPRITE_LARGE_LOWDENSITY_INDUSTRIALZONE",
	"SPRITE_LARGE_HIGHDENSITY_INDUSTRIALZONE",
	"SPRITE_LARGE_MILITARYZONE",
	"SPRITE_LARGE_AIRPORTZONE",
	"SPRITE_LARGE_SEAPORTZONE",
	"SPRITE_LARGE_GREENTILE",
	"SPRITE_LARGE_BLUETILE",
	"SPRITE_LARGE_YELLOWTILE",
	"SPRITE_LARGE_REDTILE",
	"SPRITE_LARGE_GREYTILE",
	"SPRITE_LARGE_UNDERGROUND_TERRAIN",
	"SPRITE_LARGE_UNDERGROUND_TERRAIN_HTB",
	"SPRITE_LARGE_UNDERGROUND_TERRAIN_HRL",
	"SPRITE_LARGE_UNDERGROUND_TERRAIN_THB",
	"SPRITE_LARGE_UNDERGROUND_TERRAIN_RHL",
	"SPRITE_LARGE_UNDERGROUND_TERRAIN_HTHRBL",
	"SPRITE_LARGE_UNDERGROUND_TERRAIN_THRHBL",
	"SPRITE_LARGE_UNDERGROUND_TERRAIN_TRHBHL",
	"SPRITE_LARGE_UNDERGROUND_TERRAIN_HTRBHL",
	"SPRITE_LARGE_UNDERGROUND_TERRAINSLOPE_HTHRBL",
	"SPRITE_LARGE_UNDERGROUND_TERRAINSLOPE_THRHBL",
	"SPRITE_LARGE_UNDERGROUND_TERRAINSLOPE_TRHBHL",
	"SPRITE_LARGE_UNDERGROUND_TERRAINSLOPE_HTRBHL",
	"SPRITE_LARGE_BEDROCK_OUTLINE",
	"SPRITE_LARGE_SUBWAY_LR",
	"SPRITE_LARGE_SUBWAY_TB",
	"SPRITE_LARGE_SUBWAY_HTB",
	"SPRITE_LARGE_SUBWAY_LHR",
	"SPRITE_LARGE_SUBWAY_THB",
	"SPRITE_LARGE_SUBWAY_HLR",
	"SPRITE_LARGE_SUBWAY_BR",
	"SPRITE_LARGE_SUBWAY_BL",
	"SPRITE_LARGE_SUBWAY_TL",
	"SPRITE_LARGE_SUBWAY_TR",
	"SPRITE_LARGE_SUBWAY_RTB",
	"SPRITE_LARGE_SUBWAY_LBR",
	"SPRITE_LARGE_SUBWAY_TLB",
	"SPRITE_LARGE_SUBWAY_LTR",
	"SPRITE_LARGE_SUBWAY_LTBR",
	"SPRITE_LARGE_PIPES_LR",
	"SPRITE_LARGE_PIPES_TB",
	"SPRITE_LARGE_PIPES_HTB",
	"SPRITE_LARGE_PIPES_LHR",
	"SPRITE_LARGE_PIPES_THB",
	"SPRITE_LARGE_PIPES_HLR",
	"SPRITE_LARGE_PIPES_BR",
	"SPRITE_LARGE_PIPES_BL",
	"SPRITE_LARGE_PIPES_TL",
	"SPRITE_LARGE_PIPES_TR",
	"SPRITE_LARGE_PIPES_RTB",
	"SPRITE_LARGE_PIPES_LBR",
	"SPRITE_LARGE_PIPES_TLB",
	"SPRITE_LARGE_PIPES_LTR",
	"SPRITE_LARGE_PIPES_LTBR",
	"SPRITE_LARGE_CROSSOVER_PIPESTB_SUBWAYLR",
	"SPRITE_LARGE_CROSSOVER_PIPESLR_SUBWAYTB",
	"SPRITE_LARGE_BUILDINGPIPE",
	"SPRITE_LARGE_MISSILESILO",
	"SPRITE_LARGE_SUBWAYENTRANCE",
	"SPRITE_LARGE_GREENOUTLINE",
	"SPRITE_LARGE_BLUEOUTLINE",
	"SPRITE_LARGE_BROWNOUTLINE",
	"SPRITE_LARGE_REDOUTLINE",
	"SPRITE_LARGE_GREYOUTLINE",
	"SPRITE_LARGE_AIRPLANE_N",
	"SPRITE_LARGE_AIRPLANE_NE",
	"SPRITE_LARGE_AIRPLANE_E",
	"SPRITE_LARGE_AIRPLANE_SE",
	"SPRITE_LARGE_AIRPLANE_S",
	"SPRITE_LARGE_SIMCOPTER_N",
	"SPRITE_LARGE_SIMCOPTER_NE",
	"SPRITE_LARGE_SIMCOPTER_E",
	"SPRITE_LARGE_SIMCOPTER_SE",
	"SPRITE_LARGE_SIMCOPTER_S",
	"SPRITE_LARGE_CARGOSHIP_N",
	"SPRITE_LARGE_CARGOSHIP_NE",
	"SPRITE_LARGE_CARGOSHIP_E",
	"SPRITE_LARGE_CARGOSHIP_SE",
	"SPRITE_LARGE_CARGOSHIP_S",
	"SPRITE_LARGE_TRAIN_N",
	"SPRITE_LARGE_TRAIN_NE",
	"SPRITE_LARGE_TRAIN_E",
	"SPRITE_LARGE_TRAIN_SE",
	"SPRITE_LARGE_TRAIN_S",
	"SPRITE_LARGE_NESSIE",
	"SPRITE_LARGE_SAILBOAT_NE",
	"SPRITE_LARGE_SAILBOAT_SE",
	"SPRITE_LARGE_POLICE_DISPATCH",
	"SPRITE_LARGE_FIREDEPT_DISPATCH",
	"SPRITE_LARGE_MILITARY_DISPATCH",
	"SPRITE_LARGE_MONSTERSPACERAY",
	"SPRITE_LARGE_POWEROUTAGEINDICATOR",
	"SPRITE_LARGE_EXPLOSION1",
	"SPRITE_LARGE_EXPLOSION2",
	"SPRITE_LARGE_EXPLOSION3",
	"SPRITE_LARGE_BULLDOZER_NE",
	"SPRITE_LARGE_BULLDOZER_SE",
	"SPRITE_LARGE_DUSTCLOUD1",
	"SPRITE_LARGE_DUSTCLOUD2",
	"SPRITE_LARGE_DUSTCLOUD3",
	"SPRITE_LARGE_DUSTCLOUD4",
	"SPRITE_LARGE_FIRE1",
	"SPRITE_LARGE_FIRE2",
	"SPRITE_LARGE_FIRE3",
	"SPRITE_LARGE_FIRE4",
	"SPRITE_LARGE_ROADLIGHTTRAFFIC_RL",
	"SPRITE_LARGE_ROADLIGHTTRAFFIC_TB",
	"SPRITE_LARGE_ROADLIGHTTRAFFIC_HTB",
	"SPRITE_LARGE_ROADLIGHTTRAFFIC_HRL",
	"SPRITE_LARGE_ROADLIGHTTRAFFIC_THB",
	"SPRITE_LARGE_ROADLIGHTTRAFFIC_RHL",
	"SPRITE_LARGE_ROADLIGHTTRAFFIC_RB",
	"SPRITE_LARGE_ROADLIGHTTRAFFIC_BL",
	"SPRITE_LARGE_ROADLIGHTTRAFFIC_TL",
	"SPRITE_LARGE_ROADLIGHTTRAFFIC_TR",
	"SPRITE_LARGE_HIGHWAYLIGHTTRAFFIC_RL",
	"SPRITE_LARGE_HIGHWAYLIGHTTRAFFIC_TB",
	"SPRITE_LARGE_CAUSEWAYLIGHTTRAFFIC_RL",
	"SPRITE_LARGE_CAUSEWAYLIGHTTRAFFIC_TB",
	"SPRITE_LARGE_HIGHWAYONRAMPLIGHTTRAFFIC_RB",
	"SPRITE_LARGE_HIGHWAYONRAMPLIGHTTRAFFIC_TR",
	"SPRITE_LARGE_HIGHWAYONRAMPLIGHTTRAFFIC_RT",
	"SPRITE_LARGE_HIGHWAYONRAMPLIGHTTRAFFIC_BL",
	"SPRITE_LARGE_HIGHWAYLIGHTTRAFFIC_HTB",
	"SPRITE_LARGE_HIGHWAYLIGHTTRAFFIC_HRL",
	"SPRITE_LARGE_HIGHWAYLIGHTTRAFFIC_THB",
	"SPRITE_LARGE_HIGHWAYLIGHTTRAFFIC_RHL",
	"SPRITE_LARGE_HIGHWAYLIGHTTRAFFIC_RB",
	"SPRITE_LARGE_HIGHWAYLIGHTTRAFFIC_BL",
	"SPRITE_LARGE_HIGHWAYLIGHTTRAFFIC_TL",
	"SPRITE_LARGE_HIGHWAYLIGHTTRAFFIC_TR",
	"SPRITE_LARGE_HIGHWAYINTERCHANGELIGHTTRAFFIC_TRBL",
	"SPRITE_LARGE_ROADHEAVYTRAFFIC_RL",
	"SPRITE_LARGE_ROADHEAVYTRAFFIC_TB",
	"SPRITE_LARGE_ROADHEAVYTRAFFIC_HTB",
	"SPRITE_LARGE_ROADHEAVYTRAFFIC_HRL",
	"SPRITE_LARGE_ROADHEAVYTRAFFIC_THB",
	"SPRITE_LARGE_ROADHEAVYTRAFFIC_RHL",
	"SPRITE_LARGE_ROADHEAVYTRAFFIC_RB",
	"SPRITE_LARGE_ROADHEAVYTRAFFIC_BL",
	"SPRITE_LARGE_ROADHEAVYTRAFFIC_TL",
	"SPRITE_LARGE_ROADHEAVYTRAFFIC_TR",
	"SPRITE_LARGE_HIGHWAYHEAVYTRAFFIC_RL",
	"SPRITE_LARGE_HIGHWAYHEAVYTRAFFIC_TB",
	"SPRITE_LARGE_CAUSEWAYHEAVYTRAFFIC_RL",
	"SPRITE_LARGE_CAUSEWAYHEAVYTRAFFIC_TB",
	"SPRITE_LARGE_HIGHWAYHEAVYTRAFFIC_HTB",
	"SPRITE_LARGE_HIGHWAYHEAVYTRAFFIC_HRL",
	"SPRITE_LARGE_HIGHWAYHEAVYTRAFFIC_THB",
	"SPRITE_LARGE_HIGHWAYHEAVYTRAFFIC_RHL",
	"SPRITE_LARGE_HIGHWAYHEAVYTRAFFIC_RB",
	"SPRITE_LARGE_HIGHWAYHEAVYTRAFFIC_BL",
	"SPRITE_LARGE_HIGHWAYHEAVYTRAFFIC_TL",
	"SPRITE_LARGE_HIGHWAYHEAVYTRAFFIC_TR",
	"SPRITE_LARGE_HIGHWAYHEAVYTRAFFIC_TRBL",
	"SPRITE_LARGE_PIPEWATERED_RL",
	"SPRITE_LARGE_PIPEWATERED_TB",
	"SPRITE_LARGE_PIPEWATERED_HTB",
	"SPRITE_LARGE_PIPEWATERED_HRL",
	"SPRITE_LARGE_PIPEWATERED_THB",
	"SPRITE_LARGE_PIPEWATERED_RHL",
	"SPRITE_LARGE_PIPEWATERED_RB",
	"SPRITE_LARGE_PIPEWATERED_BL",
	"SPRITE_LARGE_PIPEWATERED_TL",
	"SPRITE_LARGE_PIPEWATERED_TR",
	"SPRITE_LARGE_PIPEWATERED_TRB",
	"SPRITE_LARGE_PIPEWATERED_RBL",
	"SPRITE_LARGE_PIPEWATERED_TBL",
	"SPRITE_LARGE_PIPEWATERED_TRL",
	"SPRITE_LARGE_PIPEWATERED_TRBL",
	"SPRITE_LARGE_SUBWAY_RL_PIPEWATERED_TB",
	"SPRITE_LARGE_SUBWAY_TB_PIPEWATERED_RL",
	"SPRITE_LARGE_BUILDINGPIPEWATERED_TRBL",
	"SPRITE_LARGE_DENSITYOVERLAY1",
	"SPRITE_LARGE_DENSITYOVERLAY2",
	"SPRITE_LARGE_DENSITYOVERLAY3",
	"SPRITE_LARGE_DENSITYOVERLAY4",
	"SPRITE_LARGE_DENSITYOVERLAY5",
	"SPRITE_LARGE_DENSITYOVERLAY6",
	"SPRITE_LARGE_DENSITYOVERLAY7",
	"SPRITE_LARGE_DENSITYOVERLAY8",
	"SPRITE_LARGE_GREENPLUS",
	"SPRITE_LARGE_REDNEGATIVE",
	"SPRITE_LARGE_MONSTERPARTS1",
	"SPRITE_LARGE_MONSTERPARTS2",
	"SPRITE_LARGE_MONSTERPARTS3",
	"SPRITE_LARGE_MONSTERPARTS4",
	"SPRITE_LARGE_MONSTERPARTS5",
	"SPRITE_LARGE_MONSTERPARTS6",
	"SPRITE_LARGE_MONSTERPARTS7",
	"SPRITE_LARGE_MONSTERPARTS8",
	"SPRITE_LARGE_MONSTERPARTS9",
	"SPRITE_LARGE_MONSTERPARTS10",
	"SPRITE_LARGE_MONSTERPARTS11",
	"SPRITE_LARGE_MONSTERPARTS12",
	"SPRITE_LARGE_MONSTERPARTS13",
	"SPRITE_LARGE_MONSTERPARTS14",
	"SPRITE_LARGE_FLOODWATER",
	"SPRITE_LARGE_RIOTERS1",
	"SPRITE_LARGE_RIOTERS2",
	"SPRITE_LARGE_MAXISMAN",
	"SPRITE_LARGE_DUSTCLOUD",
	"SPRITE_LARGE_TORNADO1",
	"SPRITE_LARGE_TORNADO2",
	"SPRITE_LARGE_TORNADO3"
};

const char* szUndergroundNames[36] = {
	"Bedrock Outline",

	"Subway (LR)",
	"Subway (TB)",
	"Subway (HTB)",
	"Subway (LHR)",
	"Subway (THB)",
	"Subway (HLR)",
	"Subway (BR)",
	"Subway (BL)",
	"Subway (TL)",
	"Subway (TR)",
	"Subway (RTB)",
	"Subway (LBR)",
	"Subway (TLB)",
	"Subway (LTR)",
	"Subway (LTBR)",

	"Pipes (LR)",
	"Pipes (TB)",
	"Pipes (HTB)",
	"Pipes (LHR)",
	"Pipes (THB)",
	"Pipes (HLR)",
	"Pipes (BR)",
	"Pipes (BL)",
	"Pipes (TL)",
	"Pipes (TR)",
	"Pipes (RTB)",
	"Pipes (LBR)",
	"Pipes (TLB)",
	"Pipes (LTR)",
	"Pipes (LTBR)",

	"Crossover (PIPESTB_SUBWAYLR)",
	"Crossover (PIPESLR_SUBWAYTB)",
	"Unwatered Base Piping",
	"Missile Silo",
	"Subway Entrance"
};

const char* szThingNames[XTHG_COUNT] = {
	"None",
	"Aeroplane",
	"Helicopter",
	"Cargo Ship",
	"Bulldozer",
	"Monster",
	"Explosion",
	"Police Deployment",
	"Fire Deployment",
	"Sailboat",
	"Train Engine",
	"Train Car",
	"Train Engine (Subway)",
	"Train Car (Subway)",
	"Military Deployment",
	"Tornado",
	"Maxis Man"
};

const char* szThingDirectionNames[XTHG_DIRECTION_COUNT] = {
	"North",
	"North East",
	"East",
	"South East",
	"South",
	"South West",
	"West",
	"North West"
};

const char* szOnIdleStateEnums[ONIDLE_STATE_MAX] = {
	"ONIDLE_STATE_INGAME",
	"ONIDLE_STATE_MAPMODE",
	"ONIDLE_STATE_DISPLAYMAXIS",
	"ONIDLE_STATE_WAITMAXIS",
	"ONIDLE_STATE_DISPLAYTITLE",
	"ONIDLE_STATE_DIALOGFINISH",
	"ONIDLE_STATE_DISPLAYREGISTRATION",
	"ONIDLE_STATE_CLOSEREGISTRATION",
	"ONIDLE_STATE_PENDINGACTION",
	"ONIDLE_STATE_NONE_8",
	"ONIDLE_STATE_NONE_9",
	"ONIDLE_STATE_LOADCITY_RETURN",
	"ONIDLE_STATE_NEWCITY_RETURN",
	"ONIDLE_STATE_EDITNEWMAP_RETURN",
	"ONIDLE_STATE_LOADSCENARIO_RETURN",
	"ONIDLE_STATE_MENUDIALOG",
	"ONIDLE_STATE_FROMCMDLINE",
	"ONIDLE_STATE_INTROVIDEO",
	"ONIDLE_STATE_DISPLAYINFLIGHT",
	"ONIDLE_STATE_CLOSEINFLIGHT"
};

const char* szOnIdleInitialDialogEnums[ONIDLE_INITIALDIALOG_MAX] {
	"ONIDLE_INITIALDIALOG_NONE",
	"ONIDLE_INITIALDIALOG_LOADCITY",
	"ONIDLE_INITIALDIALOG_NEWCITY",
	"ONIDLE_INITIALDIALOG_EDITNEWMAP",
	"ONIDLE_INITIALDIALOG_LOADSCENARIO",
	"ONIDLE_INITIALDIALOG_ONQUIT",
	"ONIDLE_INITIALDIALOG_LOADTILESET",
	"ONIDLE_INITIALDIALOG_MOVIES",
	"ONIDLE_INITIALDIALOG_SC2KFIXSETTINGS"
};
