// sc2kfix winmm_exports.h: list of WinMM exports we need to pass through
// (c) 2025 github.com/araxestroy - released under the MIT license

#pragma once

#define ALLEXPORTS_HOOKED(f) \
    f(41, mciSendCommandA) \
    f(132, sndPlaySoundA)

#define ALLEXPORTS_PASSTHROUGH(f) \
    f(0, CloseDriver) \
    f(1, DefDriverProc) \
    f(2, DriverCallback) \
    f(3, DrvGetModuleHandle) \
    f(4, GetDriverModuleHandle) \
    f(5, OpenDriver) \
    f(6, PlaySound) \
    f(7, PlaySoundA) \
    f(8, PlaySoundW) \
    f(9, SendDriverMessage) \
    f(10, WOWAppExit) \
    f(11, auxGetDevCapsA) \
    f(12, auxGetDevCapsW) \
    f(13, auxGetNumDevs) \
    f(14, auxGetVolume) \
    f(15, auxOutMessage) \
    f(16, auxSetVolume) \
    f(17, joyConfigChanged) \
    f(18, joyGetDevCapsA) \
    f(19, joyGetDevCapsW) \
    f(20, joyGetNumDevs) \
    f(21, joyGetPos) \
    f(22, joyGetPosEx) \
    f(23, joyGetThreshold) \
    f(24, joyReleaseCapture) \
    f(25, joySetCapture) \
    f(26, joySetThreshold) \
    f(27, mciDriverNotify) \
    f(28, mciDriverYield) \
    f(29, mciExecute) \
    f(30, mciFreeCommandResource) \
    f(31, mciGetCreatorTask) \
    f(32, mciGetDeviceIDA) \
    f(33, mciGetDeviceIDFromElementIDA) \
    f(34, mciGetDeviceIDFromElementIDW) \
    f(35, mciGetDeviceIDW) \
    f(36, mciGetDriverData) \
    f(37, mciGetErrorStringA) \
    f(38, mciGetErrorStringW) \
    f(39, mciGetYieldProc) \
    f(40, mciLoadCommandResource) \
    f(42, mciSendCommandW) \
    f(43, mciSendStringA) \
    f(44, mciSendStringW) \
    f(45, mciSetDriverData) \
    f(46, mciSetYieldProc) \
    f(47, midiConnect) \
    f(48, midiDisconnect) \
    f(49, midiInAddBuffer) \
    f(50, midiInClose) \
    f(51, midiInGetDevCapsA) \
    f(52, midiInGetDevCapsW) \
    f(53, midiInGetErrorTextA) \
    f(54, midiInGetErrorTextW) \
    f(55, midiInGetID) \
    f(56, midiInGetNumDevs) \
    f(57, midiInMessage) \
    f(58, midiInOpen) \
    f(59, midiInPrepareHeader) \
    f(60, midiInReset) \
    f(61, midiInStart) \
    f(62, midiInStop) \
    f(63, midiInUnprepareHeader) \
    f(64, midiOutCacheDrumPatches) \
    f(65, midiOutCachePatches) \
    f(66, midiOutClose) \
    f(67, midiOutGetDevCapsA) \
    f(68, midiOutGetDevCapsW) \
    f(69, midiOutGetErrorTextA) \
    f(70, midiOutGetErrorTextW) \
    f(71, midiOutGetID) \
    f(72, midiOutGetNumDevs) \
    f(73, midiOutGetVolume) \
    f(74, midiOutLongMsg) \
    f(75, midiOutMessage) \
    f(76, midiOutOpen) \
    f(77, midiOutPrepareHeader) \
    f(78, midiOutReset) \
    f(79, midiOutSetVolume) \
    f(80, midiOutShortMsg) \
    f(81, midiOutUnprepareHeader) \
    f(82, midiStreamClose) \
    f(83, midiStreamOpen) \
    f(84, midiStreamOut) \
    f(85, midiStreamPause) \
    f(86, midiStreamPosition) \
    f(87, midiStreamProperty) \
    f(88, midiStreamRestart) \
    f(89, midiStreamStop) \
    f(90, mixerClose) \
    f(91, mixerGetControlDetailsA) \
    f(92, mixerGetControlDetailsW) \
    f(93, mixerGetDevCapsA) \
    f(94, mixerGetDevCapsW) \
    f(95, mixerGetID) \
    f(96, mixerGetLineControlsA) \
    f(97, mixerGetLineControlsW) \
    f(98, mixerGetLineInfoA) \
    f(99, mixerGetLineInfoW) \
    f(100, mixerGetNumDevs) \
    f(101, mixerMessage) \
    f(102, mixerOpen) \
    f(103, mixerSetControlDetails) \
    f(104, mmDrvInstall) \
    f(105, mmGetCurrentTask) \
    f(106, mmTaskBlock) \
    f(107, mmTaskCreate) \
    f(108, mmTaskSignal) \
    f(109, mmTaskYield) \
    f(110, mmioAdvance) \
    f(111, mmioAscend) \
    f(112, mmioClose) \
    f(113, mmioCreateChunk) \
    f(114, mmioDescend) \
    f(115, mmioFlush) \
    f(116, mmioGetInfo) \
    f(117, mmioInstallIOProcA) \
    f(118, mmioInstallIOProcW) \
    f(119, mmioOpenA) \
    f(120, mmioOpenW) \
    f(121, mmioRead) \
    f(122, mmioRenameA) \
    f(123, mmioRenameW) \
    f(124, mmioSeek) \
    f(125, mmioSendMessage) \
    f(126, mmioSetBuffer) \
    f(127, mmioSetInfo) \
    f(128, mmioStringToFOURCCA) \
    f(129, mmioStringToFOURCCW) \
    f(130, mmioWrite) \
    f(131, mmsystemGetVersion) \
    f(133, sndPlaySoundW) \
    f(134, timeBeginPeriod) \
    f(135, timeEndPeriod) \
    f(136, timeGetDevCaps) \
    f(137, timeGetSystemTime) \
    f(138, timeGetTime) \
    f(139, timeKillEvent) \
    f(140, timeSetEvent) \
    f(141, waveInAddBuffer) \
    f(142, waveInClose) \
    f(143, waveInGetDevCapsA) \
    f(144, waveInGetDevCapsW) \
    f(145, waveInGetErrorTextA) \
    f(146, waveInGetErrorTextW) \
    f(147, waveInGetID) \
    f(148, waveInGetNumDevs) \
    f(149, waveInGetPosition) \
    f(150, waveInMessage) \
    f(151, waveInOpen) \
    f(152, waveInPrepareHeader) \
    f(153, waveInReset) \
    f(154, waveInStart) \
    f(155, waveInStop) \
    f(156, waveInUnprepareHeader) \
    f(157, waveOutBreakLoop) \
    f(158, waveOutClose) \
    f(159, waveOutGetDevCapsA) \
    f(160, waveOutGetDevCapsW) \
    f(161, waveOutGetErrorTextA) \
    f(162, waveOutGetErrorTextW) \
    f(163, waveOutGetID) \
    f(164, waveOutGetNumDevs) \
    f(165, waveOutGetPitch) \
    f(166, waveOutGetPlaybackRate) \
    f(167, waveOutGetPosition) \
    f(168, waveOutGetVolume) \
    f(169, waveOutMessage) \
    f(170, waveOutOpen) \
    f(171, waveOutPause) \
    f(172, waveOutPrepareHeader) \
    f(173, waveOutReset) \
    f(174, waveOutRestart) \
    f(175, waveOutSetPitch) \
    f(176, waveOutSetPlaybackRate) \
    f(177, waveOutSetVolume) \
    f(178, waveOutUnprepareHeader) \
    f(179, waveOutWrite)