#pragma once

// The SC2K resource IDs are set here to make working with them slightly less of a headache.
// For the most part these are general across all Windows (95?) versions of the game.
// Any special cases (non-native or differing) will be noted down accordingly.

// This macro is used if you're accessing game menu positional indices
// via CMainFrame rather than CSimcityView.
#define SC2K_MENU_GAME_FROM_MAIN(x) (x + 1)

// Window Messages
#define WM_SC2KFIX_UPDATE		  37241 // Not native

// Dialog, Item IDs
#define SC2K_DIALOG_NEWCITY       101
#define SC2K_DIALOG_BUDGET        102
#define SC2K_DIALOG_MAIN          103
#define SC2K_DIALOG_SELECTITEM    113
#define SC2K_DIALOG_QUERYGENERAL  142
#define SC2K_DIALOG_QUERYSPECIFIC 154

// New City Dialog
#define SC2K_DIALOG_NEWCITY_BTN_REGENERATE    20   // Not native
#define SC2K_DIALOG_NEWCITY_EDIT_CITYNAME     101
#define SC2K_DIALOG_NEWCITY_RADIO_YEAR1900    104
#define SC2K_DIALOG_NEWCITY_RADIO_YEAR1950    105
#define SC2K_DIALOG_NEWCITY_RADIO_YEAR2000    106
#define SC2K_DIALOG_NEWCITY_RADIO_YEAR2050    107
#define SC2K_DIALOG_NEWCITY_RADIO_TRRNCLASSIC 108 // Not native
#define SC2K_DIALOG_NEWCITY_RADIO_DIFFEASY    109
#define SC2K_DIALOG_NEWCITY_RADIO_DIFFMEDIUM  110
#define SC2K_DIALOG_NEWCITY_RADIO_DIFFHARD    111
#define SC2K_DIALOG_NEWCITY_RADIO_TRRNGREY    112  // Not native
#define SC2K_DIALOG_NEWCITY_RADIO_TRRNLUSH    113  // Not native
#define SC2K_DIALOG_NEWCITY_RADIO_TRRNCOLD    114  // Not native
#define SC2K_DIALOG_NEWCITY_RADIO_TRRNHOT     115  // Not native
#define SC2K_DIALOG_NEWCITY_RADIO_TRRNRANDOM  116  // Not native
#define SC2K_DIALOG_NEWCITY_LBL_TRRNWARN      117  // Not native
#define SC2K_DIALOG_NEWCITY_LBL_TIP           119  // Not native
#define SC2K_DIALOG_NEWCITY_EDIT_MAYORNAME    150  // Not native
#define SC2K_DIALOG_NEWCITY_LBL_DIFFEASY      1001 // Not native
#define SC2K_DIALOG_NEWCITY_LBL_DIFFMEDIUM    1002 // Not native
#define SC2K_DIALOG_NEWCITY_LBL_DIFFHARD      1003 // Not native
#define SC2K_DIALOG_NEWCITY_LBL_STARTYEAR     1010 // Not native
#define SC2K_DIALOG_NEWCITY_LBL_DIFFICULTY    1011 // Not native
#define SC2K_DIALOG_NEWCITY_LBL_TRRNTYPE      1012 // Not native

// 'Main' Dialog
#define SC2K_DIALOG_MAIN_BTN_LOADCITY         111
#define SC2K_DIALOG_MAIN_BTN_NEWCITY          112
#define SC2K_DIALOG_MAIN_BTN_EDITNEWMAP       113
#define SC2K_DIALOG_MAIN_BTN_LOADSCENARIO     114
#define SC2K_DIALOG_MAIN_BTN_QUIT             115
#define SC2K_DIALOG_MAIN_BTN_LOADTILESET      116
#define SC2K_DIALOG_MAIN_BTN_WATCHTV          117
#define SC2K_DIALOG_MAIN_BTN_SC2KFIXSETTINGS  21023 // Definitely not native
#define SC2K_DIALOG_MAIN_LBL_UPDATENOTICE     21038 // Not native

// Budget Dialog
#define SC2K_DIALOG_BUDGET_EDIT_NAMEYEARMONTH     101
#define SC2K_DIALOG_BUDGET_EDIT_PROPTAX           102
#define SC2K_DIALOG_BUDGET_EDIT_POLICE            104
#define SC2K_DIALOG_BUDGET_EDIT_FIRE              105
#define SC2K_DIALOG_BUDGET_EDIT_HEALTH            106
#define SC2K_DIALOG_BUDGET_EDIT_EDUCATION         107
#define SC2K_DIALOG_BUDGET_EDIT_TRANSIT           108
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_POLICE     125
#define SC2K_DIALOG_BUDGET_BTN_FIRE               126
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_FIRE       127
#define SC2K_DIALOG_BUDGET_BTN_EDUCATION          128
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_EDUCATION  129
#define SC2K_DIALOG_BUDGET_BTN_TRANSIT            130
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_TRANSIT    131
#define SC2K_DIALOG_BUDGET_STATIC_EOYFUNDS        132
#define SC2K_DIALOG_BUDGET_STATIC_SUMMARY         133
#define SC2K_DIALOG_BUDGET_BTN_PROPTAX            134
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_PROPTAX    135
#define SC2K_DIALOG_BUDGET_BTN_HEALTH             136
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_HEALTH     137
#define SC2K_DIALOG_BUDGET_BTN_POLICE             138
#define SC2K_DIALOG_BUDGET_BTN_ORDINANCES         139
#define SC2K_DIALOG_BUDGET_BTN_BONDPAYMNT         140
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_ORDINANCES 141
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_BONDPAYMNT 142
#define SC2K_DIALOG_BUDGET_EDIT_TDE_PROPTAX       200
#define SC2K_DIALOG_BUDGET_EDIT_TDE_ORDINANCES    201
#define SC2K_DIALOG_BUDGET_EDIT_TDE_BONDPAYMNT    202
#define SC2K_DIALOG_BUDGET_EDIT_TDE_POLICE        203
#define SC2K_DIALOG_BUDGET_EDIT_TDE_FIRE          204
#define SC2K_DIALOG_BUDGET_EDIT_TDE_HEALTH        205
#define SC2K_DIALOG_BUDGET_EDIT_TDE_EDUCATION     206
#define SC2K_DIALOG_BUDGET_EDIT_TDE_TRANSIT       207
#define SC2K_DIALOG_BUDGET_EDIT_YEE_PROPTAX       210
#define SC2K_DIALOG_BUDGET_EDIT_YEE_ORDINANCES    211
#define SC2K_DIALOG_BUDGET_EDIT_YEE_BONDPAYMNT    212
#define SC2K_DIALOG_BUDGET_EDIT_YEE_POLICE        213
#define SC2K_DIALOG_BUDGET_EDIT_YEE_FIRE          214
#define SC2K_DIALOG_BUDGET_EDIT_YEE_HEALTH        215
#define SC2K_DIALOG_BUDGET_EDIT_YEE_EDUCATION     216
#define SC2K_DIALOG_BUDGET_EDIT_YEE_TRANSIT       217
#define SC2K_DIALOG_BUDGET_STRING_TDE             305
#define SC2K_DIALOG_BUDGET_STRING_YEE             306
#define SC2K_DIALOG_BUDGET_STATIC_HOURGLASS       336
#define SC2K_DIALOG_BUDGET_LBL_PROPTAX            350   // Not native
#define SC2K_DIALOG_BUDGET_LBL_ORDINANCES         351   // Not native
#define SC2K_DIALOG_BUDGET_LBL_BINDPAYMNT         352   // Not native
#define SC2K_DIALOG_BUDGET_LBL_POLICE             353   // Not native
#define SC2K_DIALOG_BUDGET_LBL_FIRE               354   // Not native
#define SC2K_DIALOG_BUDGET_LBL_HEALTH             355   // Not native
#define SC2K_DIALOG_BUDGET_LBL_EDUCATION          356   // Not native
#define SC2K_DIALOG_BUDGET_LBL_TRANSIT            357   // Not native
#define SC2K_DIALOG_BUDGET_SCROLLBAR_PROPTAX      440
#define SC2K_DIALOG_BUDGET_SCROLLBAR_POLICE       441
#define SC2K_DIALOG_BUDGET_SCROLLBAR_FIRE         442
#define SC2K_DIALOG_BUDGET_SCROLLBAR_EDUCATION    443
#define SC2K_DIALOG_BUDGET_SCROLLBAR_TRANSIT      444
#define SC2K_DIALOG_BUDGET_SCROLLBAR_HEALTH       445
#define SC2K_DIALOG_BUDGET_HELP                   21098 // Not native

// Menu IDs
#define SC2K_MENU_MAIN            2
#define SC2K_MENU_GAME            3
#define SC2K_MENU_CITYTOOLBAR     136
#define SC2K_MENU_RCLKSHORTCUT    243

// Sub-menu IDs
// MainFrame
#define SC2K_MENU_MAIN_FILE       0
#define SC2K_MENU_MAIN_HELP       1
// SimcityView
#define SC2K_MENU_GAME_FILE       0
#define SC2K_MENU_GAME_SPEED      1
#define SC2K_MENU_GAME_OPTIONS    2
#define SC2K_MENU_GAME_DISASTERS  3
#define SC2K_MENU_GAME_WINDOWS    4
#define SC2K_MENU_GAME_PAPERS     5
#define SC2K_MENU_GAME_HELP_NODBG 6 // This is the position if the debug menu isn't attached and active.
#define SC2K_MENU_GAME_DEBUG      6
#define SC2K_MENU_GAME_HELP       7

// String IDs
