#pragma once

// The SC2K resource IDs are set here to make working with them slightly less of a headache.
// For the most part these are general across all Windows (95?) versions of the game.
// Any special cases (non-native or differing) will be noted down accordingly.

// This macro is used if you're accessing game menu positional indices
// via CMainFrame rather than CSimcityView.
#define SC2K_MENU_GAME_FROM_MAIN(x) (x + 1)

// Window Messages
#define WM_SC2KFIX_UPDATE		  37241 // Not native

// Dialog, Item IDs
#define SC2K_DIALOG_NEWCITY       101
#define SC2K_DIALOG_BUDGET        102
#define SC2K_DIALOG_MAIN          103
#define SC2K_DIALOG_OWNER         106
#define SC2K_DIALOG_SELECTITEM    113
#define SC2K_DIALOG_ORDINANCES    119
#define SC2K_DIALOG_POPULATION    128
#define SC2K_DIALOG_QUERYGENERAL  142
#define SC2K_DIALOG_GRAPH         152
#define SC2K_DIALOG_QUERYSPECIFIC 154
#define SC2K_DIALOG_NEIGHBORS     157
#define SC2K_DIALOG_INDUSTRY      160
#define SC2K_DIALOG_CITYMAP       246
#define SC2K_DIALOG_STATUSBAR     255

// Internal define for the Status Control Bar
#define SC2K_STATUSBAR            111

// New City Dialog
#define SC2K_DIALOG_NEWCITY_BTN_REGENERATE    20   // Not native
#define SC2K_DIALOG_NEWCITY_EDIT_CITYNAME     101
#define SC2K_DIALOG_NEWCITY_RADIO_YEAR1900    104
#define SC2K_DIALOG_NEWCITY_RADIO_YEAR1950    105
#define SC2K_DIALOG_NEWCITY_RADIO_YEAR2000    106
#define SC2K_DIALOG_NEWCITY_RADIO_YEAR2050    107
#define SC2K_DIALOG_NEWCITY_RADIO_TRRNCLASSIC 108 // Not native
#define SC2K_DIALOG_NEWCITY_RADIO_DIFFEASY    109
#define SC2K_DIALOG_NEWCITY_RADIO_DIFFMEDIUM  110
#define SC2K_DIALOG_NEWCITY_RADIO_DIFFHARD    111
#define SC2K_DIALOG_NEWCITY_RADIO_TRRNGREY    112  // Not native
#define SC2K_DIALOG_NEWCITY_RADIO_TRRNLUSH    113  // Not native
#define SC2K_DIALOG_NEWCITY_RADIO_TRRNCOLD    114  // Not native
#define SC2K_DIALOG_NEWCITY_RADIO_TRRNHOT     115  // Not native
#define SC2K_DIALOG_NEWCITY_RADIO_TRRNRANDOM  116  // Not native
#define SC2K_DIALOG_NEWCITY_LBL_TRRNWARN      117  // Not native
#define SC2K_DIALOG_NEWCITY_LBL_TIP           119  // Not native
#define SC2K_DIALOG_NEWCITY_EDIT_MAYORNAME    150  // Not native
#define SC2K_DIALOG_NEWCITY_LBL_DIFFEASY      1001 // Not native
#define SC2K_DIALOG_NEWCITY_LBL_DIFFMEDIUM    1002 // Not native
#define SC2K_DIALOG_NEWCITY_LBL_DIFFHARD      1003 // Not native
#define SC2K_DIALOG_NEWCITY_LBL_STARTYEAR     1010 // Not native
#define SC2K_DIALOG_NEWCITY_LBL_DIFFICULTY    1011 // Not native
#define SC2K_DIALOG_NEWCITY_LBL_TRRNTYPE      1012 // Not native

// 'Main' Dialog
#define SC2K_DIALOG_MAIN_BTN_LOADCITY         111
#define SC2K_DIALOG_MAIN_BTN_NEWCITY          112
#define SC2K_DIALOG_MAIN_BTN_EDITNEWMAP       113
#define SC2K_DIALOG_MAIN_BTN_LOADSCENARIO     114
#define SC2K_DIALOG_MAIN_BTN_QUIT             115
#define SC2K_DIALOG_MAIN_BTN_LOADTILESET      116
#define SC2K_DIALOG_MAIN_BTN_WATCHTV          117
#define SC2K_DIALOG_MAIN_BTN_SC2KFIXSETTINGS  21023 // Definitely not native
#define SC2K_DIALOG_MAIN_LBL_UPDATENOTICE     21038 // Not native

// 'Owner' Dialog
#define SC2K_DIALOG_OWNER_LBL_MAYORNAME       139

// 'Select Item' Dialog
// This one is used for arcologies, bridges and power plants,
// The first set of defines will be for the general IDs used in the resource.
// The next sets are specific to the target dialog use-cases.
#define SC2K_DIALOG_SELECTITEM_BTN_INFO_ONE       3
#define SC2K_DIALOG_SELECTITEM_BTN_INFO_TWO       4
#define SC2K_DIALOG_SELECTITEM_BTN_INFO_THREE     5
#define SC2K_DIALOG_SELECTITEM_BTN_INFO_FOUR      6
#define SC2K_DIALOG_SELECTITEM_BTN_INFO_FIVE      7
#define SC2K_DIALOG_SELECTITEM_BTN_INFO_SIX       8
#define SC2K_DIALOG_SELECTITEM_BTN_INFO_SEVEN     9
#define SC2K_DIALOG_SELECTITEM_BTN_INFO_EIGHT     10
#define SC2K_DIALOG_SELECTITEM_BTN_INFO_NINE      11
#define SC2K_DIALOG_SELECTITEM_BTN_INFO_TEN       12  // Not native
#define SC2K_DIALOG_SELECTITEM_BTN_ONE            120
#define SC2K_DIALOG_SELECTITEM_BTN_TWO            121
#define SC2K_DIALOG_SELECTITEM_BTN_THREE          122
#define SC2K_DIALOG_SELECTITEM_BTN_FOUR           123
#define SC2K_DIALOG_SELECTITEM_BTN_FIVE           124
#define SC2K_DIALOG_SELECTITEM_BTN_SIX            125
#define SC2K_DIALOG_SELECTITEM_BTN_SEVEN          126
#define SC2K_DIALOG_SELECTITEM_BTN_EIGHT          127
#define SC2K_DIALOG_SELECTITEM_BTN_NINE           128
#define SC2K_DIALOG_SELECTITEM_BTN_TEN            129 // Not native
#define SC2K_DIALOG_SELECTITEM_GROUPBOX_ONE       331
#define SC2K_DIALOG_SELECTITEM_GROUPBOX_TWO       332
#define SC2K_DIALOG_SELECTITEM_GROUPBOX_THREE     333
#define SC2K_DIALOG_SELECTITEM_GROUPBOX_FOUR      335
#define SC2K_DIALOG_SELECTITEM_GROUPBOX_FIVE      336
#define SC2K_DIALOG_SELECTITEM_GROUPBOX_SIX       337
#define SC2K_DIALOG_SELECTITEM_GROUPBOX_SEVEN     338
#define SC2K_DIALOG_SELECTITEM_GROUPBOX_EIGHT     339
#define SC2K_DIALOG_SELECTITEM_GROUPBOX_NINE      340
#define SC2K_DIALOG_SELECTITEM_GROUPBOX_TEN       341 // Not native

// -- Arcology
#define SC2K_DIALOG_SELECTITEM_ARCO_BTN_INFO_ONE         SC2K_DIALOG_SELECTITEM_BTN_INFO_ONE
#define SC2K_DIALOG_SELECTITEM_ARCO_BTN_INFO_TWO         SC2K_DIALOG_SELECTITEM_BTN_INFO_TWO
#define SC2K_DIALOG_SELECTITEM_ARCO_BTN_INFO_THREE       SC2K_DIALOG_SELECTITEM_BTN_INFO_THREE
#define SC2K_DIALOG_SELECTITEM_ARCO_BTN_INFO_FOUR        SC2K_DIALOG_SELECTITEM_BTN_INFO_TEN
#define SC2K_DIALOG_SELECTITEM_ARCO_BTN_ONE              SC2K_DIALOG_SELECTITEM_BTN_ONE
#define SC2K_DIALOG_SELECTITEM_ARCO_BTN_TWO              SC2K_DIALOG_SELECTITEM_BTN_TWO
#define SC2K_DIALOG_SELECTITEM_ARCO_BTN_THREE            SC2K_DIALOG_SELECTITEM_BTN_THREE
#define SC2K_DIALOG_SELECTITEM_ARCO_BTN_FOUR             SC2K_DIALOG_SELECTITEM_BTN_TEN

// -- Bridge
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_INFO_ONE       SC2K_DIALOG_SELECTITEM_BTN_INFO_ONE
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_INFO_TWO       SC2K_DIALOG_SELECTITEM_BTN_INFO_TWO
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_INFO_THREE     SC2K_DIALOG_SELECTITEM_BTN_INFO_THREE
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_INFO_FOUR      SC2K_DIALOG_SELECTITEM_BTN_INFO_FOUR
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_INFO_FIVE      SC2K_DIALOG_SELECTITEM_BTN_INFO_FIVE
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_INFO_SIX       SC2K_DIALOG_SELECTITEM_BTN_INFO_SIX
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_INFO_SEVEN     SC2K_DIALOG_SELECTITEM_BTN_INFO_SEVEN
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_ONE            SC2K_DIALOG_SELECTITEM_BTN_ONE
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_TWO            SC2K_DIALOG_SELECTITEM_BTN_TWO
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_THREE          SC2K_DIALOG_SELECTITEM_BTN_THREE
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_FOUR           SC2K_DIALOG_SELECTITEM_BTN_FOUR
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_FIVE           SC2K_DIALOG_SELECTITEM_BTN_FIVE
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_SIX            SC2K_DIALOG_SELECTITEM_BTN_SIX
#define SC2K_DIALOG_SELECTITEM_BRIDGE_BTN_SEVEN          SC2K_DIALOG_SELECTITEM_BTN_SEVEN
#define SC2K_DIALOG_SELECTITEM_BRIDGE_GROUPBOX_ONE       SC2K_DIALOG_SELECTITEM_GROUPBOX_ONE
#define SC2K_DIALOG_SELECTITEM_BRIDGE_GROUPBOX_TWO       SC2K_DIALOG_SELECTITEM_GROUPBOX_TWO
#define SC2K_DIALOG_SELECTITEM_BRIDGE_GROUPBOX_THREE     SC2K_DIALOG_SELECTITEM_GROUPBOX_THREE
#define SC2K_DIALOG_SELECTITEM_BRIDGE_GROUPBOX_FOUR      SC2K_DIALOG_SELECTITEM_GROUPBOX_FOUR
#define SC2K_DIALOG_SELECTITEM_BRIDGE_GROUPBOX_FIVE      SC2K_DIALOG_SELECTITEM_GROUPBOX_FIVE
#define SC2K_DIALOG_SELECTITEM_BRIDGE_GROUPBOX_SIX       SC2K_DIALOG_SELECTITEM_GROUPBOX_SIX
#define SC2K_DIALOG_SELECTITEM_BRIDGE_GROUPBOX_SEVEN     SC2K_DIALOG_SELECTITEM_GROUPBOX_SEVEN

// Budget Dialog
#define SC2K_DIALOG_BUDGET_EDIT_NAMEYEARMONTH     101
#define SC2K_DIALOG_BUDGET_EDIT_PROPTAX           102
#define SC2K_DIALOG_BUDGET_EDIT_POLICE            104
#define SC2K_DIALOG_BUDGET_EDIT_FIRE              105
#define SC2K_DIALOG_BUDGET_EDIT_HEALTH            106
#define SC2K_DIALOG_BUDGET_EDIT_EDUCATION         107
#define SC2K_DIALOG_BUDGET_EDIT_TRANSIT           108
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_POLICE     125
#define SC2K_DIALOG_BUDGET_BTN_FIRE               126
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_FIRE       127
#define SC2K_DIALOG_BUDGET_BTN_EDUCATION          128
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_EDUCATION  129
#define SC2K_DIALOG_BUDGET_BTN_TRANSIT            130
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_TRANSIT    131
#define SC2K_DIALOG_BUDGET_STATIC_EOYFUNDS        132
#define SC2K_DIALOG_BUDGET_STATIC_SUMMARY         133
#define SC2K_DIALOG_BUDGET_BTN_PROPTAX            134
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_PROPTAX    135
#define SC2K_DIALOG_BUDGET_BTN_HEALTH             136
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_HEALTH     137
#define SC2K_DIALOG_BUDGET_BTN_POLICE             138
#define SC2K_DIALOG_BUDGET_BTN_ORDINANCES         139
#define SC2K_DIALOG_BUDGET_BTN_BONDPAYMNT         140
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_ORDINANCES 141
#define SC2K_DIALOG_BUDGET_BTN_ADVISOR_BONDPAYMNT 142
#define SC2K_DIALOG_BUDGET_EDIT_TDE_PROPTAX       200
#define SC2K_DIALOG_BUDGET_EDIT_TDE_ORDINANCES    201
#define SC2K_DIALOG_BUDGET_EDIT_TDE_BONDPAYMNT    202
#define SC2K_DIALOG_BUDGET_EDIT_TDE_POLICE        203
#define SC2K_DIALOG_BUDGET_EDIT_TDE_FIRE          204
#define SC2K_DIALOG_BUDGET_EDIT_TDE_HEALTH        205
#define SC2K_DIALOG_BUDGET_EDIT_TDE_EDUCATION     206
#define SC2K_DIALOG_BUDGET_EDIT_TDE_TRANSIT       207
#define SC2K_DIALOG_BUDGET_EDIT_YEE_PROPTAX       210
#define SC2K_DIALOG_BUDGET_EDIT_YEE_ORDINANCES    211
#define SC2K_DIALOG_BUDGET_EDIT_YEE_BONDPAYMNT    212
#define SC2K_DIALOG_BUDGET_EDIT_YEE_POLICE        213
#define SC2K_DIALOG_BUDGET_EDIT_YEE_FIRE          214
#define SC2K_DIALOG_BUDGET_EDIT_YEE_HEALTH        215
#define SC2K_DIALOG_BUDGET_EDIT_YEE_EDUCATION     216
#define SC2K_DIALOG_BUDGET_EDIT_YEE_TRANSIT       217
#define SC2K_DIALOG_BUDGET_STRING_TDE             305
#define SC2K_DIALOG_BUDGET_STRING_YEE             306
#define SC2K_DIALOG_BUDGET_STATIC_HOURGLASS       336
#define SC2K_DIALOG_BUDGET_LBL_PROPTAX            350   // Not native
#define SC2K_DIALOG_BUDGET_LBL_ORDINANCES         351   // Not native
#define SC2K_DIALOG_BUDGET_LBL_BINDPAYMNT         352   // Not native
#define SC2K_DIALOG_BUDGET_LBL_POLICE             353   // Not native
#define SC2K_DIALOG_BUDGET_LBL_FIRE               354   // Not native
#define SC2K_DIALOG_BUDGET_LBL_HEALTH             355   // Not native
#define SC2K_DIALOG_BUDGET_LBL_EDUCATION          356   // Not native
#define SC2K_DIALOG_BUDGET_LBL_TRANSIT            357   // Not native
#define SC2K_DIALOG_BUDGET_SCROLLBAR_PROPTAX      440
#define SC2K_DIALOG_BUDGET_SCROLLBAR_POLICE       441
#define SC2K_DIALOG_BUDGET_SCROLLBAR_FIRE         442
#define SC2K_DIALOG_BUDGET_SCROLLBAR_EDUCATION    443
#define SC2K_DIALOG_BUDGET_SCROLLBAR_TRANSIT      444
#define SC2K_DIALOG_BUDGET_SCROLLBAR_HEALTH       445
#define SC2K_DIALOG_BUDGET_HELP                   21098 // Not native

// Budget Ordinances Dialog
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_FINAN_ONEPCTSALESTAX    148
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_FINAN_LEGALIZEDGAMBLING 149
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_FINAN_PARKINGFINES      150
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_FINAN_ONEPCTINCOMETAX   151
#define SC2K_DIALOG_ORDINANCES_EDIT_FINAN_ONEPCTSALESTAX        152
#define SC2K_DIALOG_ORDINANCES_EDIT_FINAN_ONEPCTINCOMETAX       153
#define SC2K_DIALOG_ORDINANCES_EDIT_FINAN_LEGALIZEGAMBLING      154
#define SC2K_DIALOG_ORDINANCES_EDIT_FINAN_PARKINGFINES          155
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_HLSFT_VOLUNTEERFIREDEPT 156
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_HLSFT_PUBLICSMOKINGBAN  157
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_HLSFT_FREECLINICS       158
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_HLSFT_JUNIORSPORTS      159
#define SC2K_DIALOG_ORDINANCES_EDIT_HLSFT_VOLUNTEERFIREDEPT     160
#define SC2K_DIALOG_ORDINANCES_EDIT_HLSFT_PUBLICSMOKINGBAN      161
#define SC2K_DIALOG_ORDINANCES_EDIT_HLSFT_FREECLINICS           162
#define SC2K_DIALOG_ORDINANCES_EDIT_HLSFT_JUNIORSPORTS          163
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_EDUCA_PROREADCAMPAIGN   164
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_EDUCA_ANTIDRUGCAMPAIGN  165
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_EDUCA_CPRTRAINING       166
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_EDUCA_NGHBRHOODWATCH    167
#define SC2K_DIALOG_ORDINANCES_EDIT_EDUCA_PROREADCAMPAIGN       168
#define SC2K_DIALOG_ORDINANCES_EDIT_EDUCA_ANTIDRUGCAMPAIGN      169
#define SC2K_DIALOG_ORDINANCES_EDIT_EDUCA_CPRTRAINING           170
#define SC2K_DIALOG_ORDINANCES_EDIT_EDUCA_NGHBRHOODWATCH        171
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_PROMO_TOURISTADVERT     172
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_PROMO_BUSINESSADVERT    173
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_PROMO_CITYBEAUTIFIC     174
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_PROMO_ANNUALCARNIVAL    175
#define SC2K_DIALOG_ORDINANCES_EDIT_PROMO_TOURISTADVERT         176
#define SC2K_DIALOG_ORDINANCES_EDIT_PROMO_BUSINESSADVERT        177
#define SC2K_DIALOG_ORDINANCES_EDIT_PROMO_CITYBEAUTIFIC         178
#define SC2K_DIALOG_ORDINANCES_EDIT_PROMO_ANNUALCARNIVAL        179
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_OTHER_ENERGYCONSERV     180
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_OTHER_NUCLEARFREEZONE   181
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_OTHER_HOMELESSSHELTER   182
#define SC2K_DIALOG_ORDINANCES_CHECKBOX_OTHER_POLLUTIONCTRLS    183
#define SC2K_DIALOG_ORDINANCES_EDIT_OTHER_ENERGYCONSERV         184
#define SC2K_DIALOG_ORDINANCES_EDIT_OTHER_NUCLEARFREEZONE       185
#define SC2K_DIALOG_ORDINANCES_EDIT_OTHER_HOMELESSSHELTER       186
#define SC2K_DIALOG_ORDINANCES_EDIT_OTHER_POLLUTIONCTRLS        187
#define SC2K_DIALOG_ORDINANCES_EDIT_INFO_FINANCE                192
#define SC2K_DIALOG_ORDINANCES_EDIT_INFO_HEALTHANDSAFETY        193
#define SC2K_DIALOG_ORDINANCES_EDIT_INFO_EDUCATION              194
#define SC2K_DIALOG_ORDINANCES_EDIT_INFO_PROMOTIONAL            195
#define SC2K_DIALOG_ORDINANCES_EDIT_INFO_OTHER                  197
#define SC2K_DIALOG_ORDINANCES_EDIT_TOTAL_YTD                   201
#define SC2K_DIALOG_ORDINANCES_EDIT_TOTAL_ESTIMATED             202

// Budget PropertyTax Dialog
#define SC2K_DIALOG_BUDGET_PROPTAX_SCROLLBAR_RES  442
#define SC2K_DIALOG_BUDGET_PROPTAX_SCROLLBAR_COM  443
#define SC2K_DIALOG_BUDGET_PROPTAX_SCROLLBAR_IND  444

// Budget Education Dialog
#define SC2K_DIALOG_BUDGET_EDUCATION_SCROLLBAR_COLLEGE 446
#define SC2K_DIALOG_BUDGET_EDUCATION_SCROLLBAR_SCHOOL  447

// Budget Transit Dialog
#define SC2K_DIALOG_BUDGET_TRANSIT_SCROLLBAR_ROAD    443
#define SC2K_DIALOG_BUDGET_TRANSIT_SCROLLBAR_RAIL    444
#define SC2K_DIALOG_BUDGET_TRANSIT_SCROLLBAR_HIGHWAY 445
#define SC2K_DIALOG_BUDGET_TRANSIT_SCROLLBAR_SUBWAY  446
#define SC2K_DIALOG_BUDGET_TRANSIT_SCROLLBAR_BRIDGE  447
#define SC2K_DIALOG_BUDGET_TRANSIT_SCROLLBAR_TUNNEL  448

// Population Dialog
#define SC2K_DIALOG_POPULATION_RADIO_POPULATION      252
#define SC2K_DIALOG_POPULATION_RADIO_HEALTH          253
#define SC2K_DIALOG_POPULATION_RADIO_EDUCATION       254
#define SC2K_DIALOG_POPULATION_STATIC                289

// Graph Dialog
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTCITYSIZE       264
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTRESIDENTS      265
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTCOMMERCE       266
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTINDUSTRY       267
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTTRAFFIC        268
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTPOLLUTION      269
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTLANDVALUE      270
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTCRIME          271
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTPOWERPERCENT   272
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTWATERPERCENT   273
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTHEALTH         274
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTEDUCATION      275
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTUNEMPLOYMENT   276
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTGNP            277
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTNATIONALPOP    278
#define SC2K_DIALOG_GRAPH_CHECKBOX_OPTFEDRATE        279
#define SC2K_DIALOG_GRAPH_RADIO_RANGEONEYEAR         280
#define SC2K_DIALOG_GRAPH_RADIO_RANGETENYEARS        281
#define SC2K_DIALOG_GRAPH_RADIO_RANGEHUNDREDYEARS    282
#define SC2K_DIALOG_GRAPH_STATIC_GRAPHAREA           283
#define SC2K_DIALOG_GRAPH_STATIC_GRAPHRANGE          284

// 'Query Specific" Dialog
#define SC2K_DIALOG_QUERYSPECIFIC_BTN_RENAME         3
#define SC2K_DIALOG_QUERYSPECIFIC_BTN_ANALYZE        120
#define SC2K_DIALOG_QUERYSPECIFIC_EDIT_LABEL         152

// Industry Dialog
#define SC2K_DIALOG_INDUSTRY_RADIO_RATIOS            291
#define SC2K_DIALOG_INDUSTRY_RADIO_TAXRATES          292
#define SC2K_DIALOG_INDUSTRY_RADIO_DEMAND            293
#define SC2K_DIALOG_INDUSTRY_STATIC_ICONS            294
#define SC2K_DIALOG_INDUSTRY_STATIC_BARS             295

// CityMap Dialog
#define SC2K_DIALOG_CITYMAP_STATIC_MAPAREA           445
#define SC2K_DIALOG_CITYMAP_TABCTRL_TABS             448
#define SC2K_DIALOG_CITYMAP_LISTBOX_SELECTION        449
#define SC2K_DIALOG_CITYMAP_BTN_SHOWCITYINWINDOW     457

// Statusbar Dialog
#define SC2K_DIALOG_STATUSBAR_BTN_GOTO               120

// Menu IDs
#define SC2K_MENU_MAIN            2
#define SC2K_MENU_GAME            3
#define SC2K_MENU_CITYTOOLBAR     136
#define SC2K_MENU_RCLKSHORTCUT    243

// Sub-menu IDs
// MainFrame
#define SC2K_MENU_MAIN_FILE       0
#define SC2K_MENU_MAIN_HELP       1
// SimcityView
#define SC2K_MENU_GAME_FILE       0
#define SC2K_MENU_GAME_SPEED      1
#define SC2K_MENU_GAME_OPTIONS    2
#define SC2K_MENU_GAME_DISASTERS  3
#define SC2K_MENU_GAME_WINDOWS    4
#define SC2K_MENU_GAME_PAPERS     5
#define SC2K_MENU_GAME_HELP_NODBG 6 // This is the position if the debug menu isn't attached and active.
#define SC2K_MENU_GAME_DEBUG      6
#define SC2K_MENU_GAME_HELP       7

// String IDs - add them as they're used and/or needed.
// *** NOTE: When it comes time to handle alternative
//           languages, highlight those that are used
//           in a given context - or if there's a
//           difference between language editions.
#define SC2K_STRING_FILECONVSIMCITY10      46
#define SC2K_STRING_ERROPENFILE            47
#define SC2K_STRING_ERRREADFILE            48
#define SC2K_STRING_ERRDECOMPFAIL          49
#define SC2K_STRING_GAMESAVEDAS            51
#define SC2K_STRING_ERRFILENOTIFF          53
#define SC2K_STRING_ERRFILENOTSC2SCN       54
#define SC2K_STRING_ERRCANNOTLOADOLDVER    55
#define SC2K_STRING_GAMENOTSAVED           60
#define SC2K_STRING_NOSCNFILESFOUND        75
#define SC2K_STRING_HYDRO                  97
#define SC2K_STRING_NOPLACEMAPEDGE         105
#define SC2K_STRING_RECONSIDERPLACE        106
#define SC2K_STRING_NOMARINAPLACE          107
#define SC2K_STRING_NOHYDROPLACE           108
#define SC2K_STRING_TUNNELNOCROSS          111
#define SC2K_STRING_TUNNELEXCEEDCITYLIM    112
#define SC2K_STRING_TUNNELTOODEEP          113
#define SC2K_STRING_TUNNELEXITUNSTABLE     114
#define SC2K_STRING_TUNNELBLOCKED          115
#define SC2K_STRING_TUNNELNOTONHILLSIDE    116
#define SC2K_STRING_NUCLEAR                129
#define SC2K_STRING_MICROWAVE              132
#define SC2K_STRING_FUSION                 133
#define SC2K_STRING_WINDOWSANCIENT         238
#define SC2K_STRING_ERRSCNRESFAILEXTRACT   239
#define SC2K_STRING_MILINTEREST            240
#define SC2K_STRING_MILARMYBASE            241
#define SC2K_STRING_MILAIRFORCE            242
#define SC2K_STRING_MILNAVALYARD           243
#define SC2K_STRING_MILMISSILESITES        244
#define SC2K_STRING_ISSUEBONDCURRATES      289
#define SC2K_STRING_OUTSTNDBONDNEEDCASH    290
#define SC2K_STRING_REPAYBONDOLDSTBONDRATE 291
#define SC2K_STRING_TUNNELBUILDENGREPORT   346
#define SC2K_STRING_MILNOSITE              411
#define SC2K_STRING_ERRLOADCITYFAIL        412
#define SC2K_STRING_TERRAINEDIT            413
#define SC2K_STRING_GROCERY                640
#define SC2K_STRING_ARCOLAUNCH             745
#define SC2K_STRING_QSANALYZE              810
#define SC2K_STRING_QSRUMINATE             811
#define SC2K_STRING_QGZONED                812
#define SC2K_STRING_QGTRAFFIC              813
#define SC2K_STRING_QGCARSPERMIN           814
#define SC2K_STRING_QGFEETDEEP             815
#define SC2K_STRING_QGLANDVALUE            816
#define SC2K_STRING_QGCRIME                817
#define SC2K_STRING_QGPOLLUTION            818
#define SC2K_STRING_QGYES                  819
#define SC2K_STRING_QGNO                   820
#define SC2K_STRING_QGWATERED              821
#define SC2K_STRING_QGGALLONSPERMON        822
#define SC2K_STRING_QGSTOREDGALLONS        823
#define SC2K_STRING_QGFEET                 824
#define SC2K_STRING_QGACRESPERTHOU         825
#define SC2K_STRING_QGPOWERED              826
#define SC2K_STRING_QGALTITUDE             827
#define SC2K_STRING_BUDGETYRENDEXPENSE     890
#define SC2K_STRING_BUDGETTODATEEST        891
#define SC2K_STRING_BUDGETEST              892
#define SC2K_STRING_BUDGETYRENDEST         893
#define SC2K_STRING_LOADCITYFILEEXTS       4002
#define SC2K_STRING_LOADSAVEDGAME          4003
#define SC2K_STRING_LOADTILEFILEEXTS       4004
#define SC2K_STRING_LOADTILESET            4005
#define SC2K_STRING_ERRNOTENOUGHMEM        4007
#define SC2K_STRING_ERRRANOUTOFMEM         4008
#define SC2K_STRING_CITYAUTOSAVEPRD        32921
