# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./sc2kfix.sln
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

jobs:
  build:
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Build Release
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}

    - name: Grab Third-Party Libraries
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        Invoke-WebRequest https://sc2kfix.net/thirdparty/LICENSES -OutFile Release/LICENSES
        Invoke-WebRequest https://sc2kfix.net/thirdparty/SDL3.dll -OutFile Release/SDL3.dll
        Invoke-WebRequest https://sc2kfix.net/thirdparty/libfluidsynth-3.dll -OutFile Release/libfluidsynth-3.dll
        Invoke-WebRequest https://sc2kfix.net/thirdparty/sndfile.dll -OutFile Release/sndfile.dll

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: sc2kfix-dev
        path: |
          Release/LICENSES
          Release/SDL3.dll
          Release/libfluidsynth-3.dll
          Release/sndfile.dll
          Release/winmm.dll
          Release/mods/*.dll
